### PR TITLE
use player character name for cyborgs

### PR DESCRIPTION
**Pull request by AriaMoradi**
## use player character name for cyborgs

**Media**

image
image

**Changelog**

:cl:
- add: Use player character name for cyborgs

### CODE REVIEW

**Review by DEATHB4DEFEAT — APPROVED** [review]
cool

**Comment by Vordenburg** [comment]
As it stands, this is not the most intuitive way to handle job-specific names. We will likely run into situations where players will spawn in with names meant for their cyborgs, and vise versa, due to the randomized nature of who may get what job at round-start and cyborgs are a job like any other.

There are plans in the works for job variants, and those plans are taking into account this very issue. That said, I am closing this PR.

**Comment by DEATHB4DEFEAT** [comment]
oh i thought this was on my repo lol

**Comment by AriaMoradi** [comment]
@Vordenburg 
I experimented with the profile UI and come up with this, is this the direction we want to go? 
It could include clown name and possibly other things in the future?
screenshot_20230204_015001

**Pull request closed without merging**
