### PR TITLE
Welders can't damage fuel tanks if not in combat mode

### PR DESCRIPTION
**Pull request by jicksaw**
## About the PR 
Trying to refill while the welder was lit would damage the fuel tank, which is an easy mistake to make. Welders can now only damage tanks when in combat mode. This aligns with most other mechanics where you have to be in combat mode to do damage.

You can't refill a welder while it's lit, and it will show a caution popup if you try. Feel free to bikeshed the message, I'm not feeling inspired so I copied [Overused Meme] (Tom Dandy)'s suggestion from Discord.

The popup is a bit hard to read because of the text color and thin font, but that's common to all caution popups.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
[Peek 2023-02-03 21-20.webm](https://user-images.githubusercontent.com/4146763/216689189-4652873d-042f-4e2b-86b3-6c29eb6ce82b.webm)

**Changelog**

:cl: jick
- tweak: Trying to refill a lit welder feels impossibly stupid now

### CODE REVIEW

**Comment by Vordenburg** [comment]
The code looks good. When I get a chance to test this locally, I'll merge if I can't find any issue.

**Comment by Vordenburg** [comment]
Everything works as intended. What do you think about having the popups occur at the cursor instead of the entity? We'll eventually need to address the contrast issue, but maybe a change of position could help.

Though I noticed PopupCursor doesn't seem to report to the chatbox, which may or may not be intended.

**Comment by jicksaw** [comment]
> Everything works as intended. What do you think about having the popups occur at the cursor instead of the entity? We'll eventually need to address the contrast issue, but maybe a change of position could help.
> 
> Though I noticed PopupCursor doesn't seem to report to the chatbox, which may or may not be intended.

I made it popup at the same location as the other welder messages. I'm open to changing just this or all of the welder messages to be at the cursor, but I think it'd be good to have them consistent with other systems.

Current caution color is pure red (FF0000). I will test some other colors to see if I can make all cautions more visible. Large cautions use bold, small and medium don't, so I'll try that too.

**Comment by Vordenburg** [comment]
The issue isn't the color, size, weight, or even the font, but the lack of text-specific contrast. All popups currently display the text as-is. For example, if there were even a drop shadow, it would improve the contrast. Ideally, we should have outlines around every popup text, especially emotes, since those can be hard to see, but this is outside the scope of this PR.

Good usage of PopupCursor vs. Entity is about where are the user's eyes at the time that the popup occurs.

**Comment by jicksaw** [comment]
Changed it to PopupCursor.

You're totally right that fixing visibility of all popups is not in scope for this PR, and that a dropshadow would fix it. I was still curious to see if changing font, color and fade speed would improve it (in this single test case ofc). Fade speed had biggest effect IME.

Maybe the message is just too long :D

### Current
https://user-images.githubusercontent.com/4146763/216825053-4284f8e5-e26e-4a5e-85b0-6289ac0ea82f.mp4

### Modified (not this PR)
https://user-images.githubusercontent.com/4146763/216825067-31f8b742-120e-42ab-b3e7-ae93eda8f936.mp4

**Comment by Vordenburg** [comment]
I agree that the fadeout, motion, and time-on-screen of popups should also be adjusted. Longer on screen, not moving away as much, and perhaps a greater limit to the alpha. The time on screen should at least be partially influenced by message length.

I think PopupCursor works well for this. Would you like to make the other popups occur at the cursor too, to be consistent?

**Comment by jicksaw** [comment]
https://user-images.githubusercontent.com/4146763/216829262-ee2feac8-3885-45b2-b055-4f71cd8bafd9.mp4

Moved all to PopupCursor except the no fuel message, since at least I always activate with Z instead of using the mouse. Also matches how stun batons report no charge left.

**Comment by Vordenburg** [comment]
> Moved all to PopupCursor except the no fuel message, since at least I always activate with Z instead of using the mouse. Also matches how stun batons report no charge left.

That seems fine to me. The general idea is to make the popup occur closest to where the player's eyes are most likely looking at the time, for any popups really, to reduce fatigue from glancing around needlessly.

**Pull request merged**
