### PR TITLE
decor skirt sprite fix

### PR DESCRIPTION
**Pull request by Plyushsune**
asdfghjkl

## About the PR 

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!

### CODE REVIEW

**Comment by Vordenburg** [comment]
What was fixed?

**Comment by Plyushsune** [comment]
> What was fixed?

it had a stray pixal on the left of the outfit

**Comment by Vordenburg** [comment]
Please try to be more descriptive initially in the future.

**Comment by Plyushsune** [comment]
> Please try to be more descriptive initially in the future.

will do

**Pull request merged**
