### PR TITLE
New Station - Angle

### PR DESCRIPTION
**Pull request by Colin-Tel**
## Added the new station Angle, with map and prototype. This time for real. A big thanks to Psprite for helping with atmos.

**Screenshots**
angle-0

**Changelog**
:cl:
- add: added new map Angle

### CODE REVIEW

**Comment by CharcoalGungan** [comment]
congrats colin

**Comment by CharcoalGungan** [comment]
CONGRATS COLIIIN

**Comment by Elijahrane** [comment]
Forbidden items I found:
- Book of Mysteries (lets people get more ifrits)
- R&D point source (should be a prober)
- Second service techfab in cargo

Other issues:
- The long hallway isn't neccesarily bad, it's the defining feature of the map, but this map will have strange atmos and so probably needs more than 8 air alarms

**Comment by Colin-Tel** [comment]
Seen, I'll correct the items and add more air alarms.

**Comment by Colin-Tel** [comment]
(not annotated above)
remove - removed forbidden items
change - changed base R&D point source to new glimmer probe

**Pull request merged**
