### PR TITLE
Add moth plushies to Space Villain arcane reward pool

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR 
Makes random normal moth plushies able to be acquired from the arcade.

**Media**

**Changelog**

:cl:
- tweak: Space Villain arcade has been restocked with normal moth plushies.

### CODE REVIEW

**Comment by Vordenburg** [comment]
I'm not a fan of referencing actual PCs in game.

**Comment by Elijahrane** [comment]
> I'm not a fan of referencing actual PCs in game.

thistbh

**Comment by FluffiestFloof** [comment]
Similar to the blue moth painting and blue moth bartender plushie, they don't have any direct references to who it represents but if you'd rather not, I'll just add the plushies to the arcade machine.

**Comment by OldDanceJacket** [comment]
> Similar to the blue moth painting and blue moth bartender plushie, they don't have any direct references to who it represents but if you'd rather not, I'll just add the plushies to the arcade machine.

Honestly those toe the line as well but we can draw the line at them. Especially with the Bartender Moth "look" being adopted by a few others. Just do the plushies in the arcade machine.

**Pull request merged**
