### PR TITLE
Evac Shuttles

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Adds two new shuttles:
The BC20 and the NTES_Seal

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Hopefully this one goes through because I need to leave for work now...

**Comment by Elijahrane** [comment]
Are these intended to be admin spawn or...?

**Comment by IamVelcroboy** [comment]
I'm not entirely sure how evac shuttles work... I asked in the Discord if there were other files/changes I need.

ODJ talked about making some map-specific but I haven't looked into how that works yet.

If there's anything else that needs to be done yet, maybe ask ODJ if he has time. Otherwise, I'm at work for the next 10 hours. So, I can make adjustments later or tomorrow. But if anyone wants to use the shuttles in the meantime, it's up to them to make it happen.

**Comment by Elijahrane** [comment]
I'll leave this PR open until that's more clear then

**Comment by IamVelcroboy** [comment]
Sounds good

**Comment by Elijahrane** [comment]
reopen when something is decided

**Pull request closed without merging**
