### PR TITLE
turtle skirt

### PR DESCRIPTION
**Pull request by Plyushsune**
this is my first real pr , be merciful: notes i wouldn't make this obtainable yet as for some reason its being weird with this one pixel being transparent.

## About the PR 

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Yukon turtleneck skirt

### CODE REVIEW

**Comment by Plyushsune** [comment]
image
image
image
image
fixed

**Comment by Plyushsune** [comment]
Ok the glitch Im reporting is apprently only on my side as colin_tel is reporting its normal on there side.

**Comment by Vordenburg** [comment]
I prefer new items to have inhand sprites. There should be some skirt inhands that you could copy and recolor. I made one for the mail carrier skirt that you could adapt based on its general shape.

This adds the item mentioned in the PR, but the item isn't available anywhere. Is there a future purpose or plan for this? Otherwise it's completely inaccessible except for an admin spawning it.

**Comment by Plyushsune** [comment]
i want to kiww mysewf smh

**Comment by Vordenburg** [comment]
The textures are in Nyano directories but the entity is in an upstream YML.

**Pull request closed without merging**
