### PR TITLE
Make HealingComponent items work on Arachne

### LINKED ISSUE #1613: HealingComponent needs to support multiple damage containers
## Description

Similar issue to https://github.com/Nyanotrasen/Nyanotrasen/issues/1612

Can be upstreamed also most likely.

### PR DESCRIPTION
**Pull request by Elijahrane**
Closes https://github.com/Nyanotrasen/Nyanotrasen/issues/1613.

:cl: Rane
- fix: Healing items can be used on arachne again.

### CODE REVIEW

**Comment by Elijahrane** [comment]
i'll probably add a spirit balm item or something in another PR to use this new feature a bit more

**Comment by Vordenburg** [comment]
When the HalfSpirit damage container was originally implemented for Arachne, the intent was to allow them to suffer Holy damage and not Genetic damage, right?

I suppose we're at one of those crossroads where we have to go one way or another in order to achieve the original goal. After reviewing this, I thought maybe the Biological set could support Holy but all original modifierSets would have to have it set to 0. However, it feels like this HealingComponent adjustment is the less invasive change.

**Comment by Vordenburg** [comment]
I've upstreamed the fix here: https://github.com/space-wizards/space-station-14/pull/16867

**Comment by Elijahrane** [comment]
after we cherry-pick again I'll just change this PR to adding half-spirit to different containers

**Comment by Vordenburg** [comment]
You should be good to go once the conflicts are resolved.

**Pull request merged**
