### PR TITLE
draft: clothing and gun

### PR DESCRIPTION
**Pull request by Plyushsune**
meow meow meow

## About the PR 

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!

### CODE REVIEW

**Comment by Vordenburg** [comment]
1. You should convert this to a draft PR if it's a draft.
2. Some description of what the goal of both the clothing and gun are would be helpful.

**Comment by Plyushsune** [comment]
> 1. You should convert this to a draft PR if it's a draft.
> 2. Some description of what the goal of both the clothing and gun are would be helpful.

this is the pr for civillian clothes

**Comment by Vordenburg** [comment]
With a gun?

**Comment by Plyushsune** [comment]
> With a gun?

i was just gonna upload them together but now thinking about it. it is best to upload both of them separately.

**Pull request closed without merging**
