### PR TITLE
Tweaked thrusters to allow large grid Shuttles/Spaceships proper movement

### PR DESCRIPTION
**Pull request by Qulibly**
## About the PR 
It influences shuttles with high amount of thrusters. As before the size (and mass) of grid had a massive impact on possible velocities while thrusters at certain point weren't able to accelerate the grid fast enough for velocity to not be reset into 0.

**Media**
obraz

**Changelog**

:cl:
- tweak: Tweaked thrusters to allow Spaceships and large shuttles to function properly

### CODE REVIEW

**Comment by Elijahrane** [comment]
mmm, with the current state of physics I am very cautious about this sort of PR.

**Comment by Vordenburg** [comment]
Undocumented magic numbers aren't so great, either.
What problem does this PR solve?

**Comment by Qulibly** [comment]
I'm trying to solve the problem which causes the large grids to be impossible to move no matter how much thrust is available for said grid.

I tried visualising the issue in video:
https://user-images.githubusercontent.com/52052459/219496502-cd9618ac-dfb4-4b4f-b239-bb9ceb729bf9.mp4

obraz


As for the way by which I'm trying to solve it.
Is by making potential max speed scale with total thrust available for the shuttle.

How it works is:

It first calculates the average thrust that one direction posseses.

For example, lets say that we use unupgraded thrusters, which posses thrust of 750 each.
So if we have 20 thrusters forward, 10 thrusters backwards, 10 thrusters left and 10 thrusters right. The resulting value would be equalivent of 12.5 thrusters.

(15 000 + 7 500 + 7 500 + 7 500) / 4 = 9 375

Then to the resulting average directional thrust I add offset. Reason for it is so that the amount of thrusters needed to raise potential max speed isn't obsenely high. 
Makes it so instead of requiring over 106 thrusters to have even slight effect. It instead start at just over 13 thrusters to have any effect.

Offset = 17 500

So in the example
9 375 + 17 500 = 26 875

After that, I divide the resulting value by 1 000. What it means is that for every   1 000 thrust the potential max speed is raised by 1. 

And at last I compare the new potential max speed with the old standard velocity for shuttles which equals 20.
Reason is that I don't want to affect the small shuttles which make up the majority of used shuttles. As otherwise they would become MUCH slower than they are currently.

So for the example:
26 875 / 1 000 = 26.875

26.875 > 20

The effect is that now example shuttle posseses higher potential max speed.



What effect potential max speed has?
First is that it works as a hard cap for shuttle's velocity. It can't accelerate to faster speeds than those by itself.
It also has influence at how fast shuttle accelerates. The higher the difference from the max, the faster acceleration will be.

Important thing of note is that large heavy grid will never be able to reach potential max speed unless it is entirely made out of thrusters. The mass simply won't allow it.


I HOPE I was able to somewhat explain what I'm trying to do.

Anyways, I would like to sincerily ask to check if the code changes are good.
As while it does work from what I tested locally, it might contain issues which I'm unaware of at the time of writing.

**Comment by Elijahrane** [comment]
bit too uncomfortable messing with this

**Pull request closed without merging**
