### PR TITLE
Atlas update

### PR DESCRIPTION
**Pull request by Pspritechologist**
:cl:
- add: Added Psychologist to prototype
- add: Added Warden to prototype
- changed: Tidied Sec slightly

### CODE REVIEW

**Comment by Nousagi37** [comment]
Noooo my OCD is going to go nuts with SEC being changed even slightly, HOW WILL I COPE WITH THIS

**Comment by Elijahrane** [comment]
isn't atlas a bit small for psychologist? Most of the roles left off were left off intentionally.
edit: remove medical cyborg while you are at it

**Comment by Pspritechologist** [comment]
> isn't atlas a bit small for psychologist? Most of the roles left off were left off intentionally. edit: remove medical cyborg while you are at it

I've been getting a lot of complaints about Warden, but if you want to hand waive that as being fine disabled, I'm cool with it.
Roleplay roles don't tend to drain from pop _too bad_ in my experience, but again, it is your call. There is a Psych office on Atlas, and Psych not being a role selectable already is actually my mistake. If you deem it away, I'll probably edit the room to be something else. I was heavily considering adding a reporter role, since I hear that one has great RP.
Are you sure about Medical Borg? I can say, with absolute definitive sureness, that there will be riots. People really like the role.

As someone who plays primarily low pop just because I really enjoy it, I have to make the argument that disabling roleplay/minor roles, such as Mediborg, Reporter, Psych, and what else doesn't end up adding to the game in the end. Leaving Chemist off (back when applicable) is a smart move, Warden can be replaced easily, etc. etc., but roles like Reporter add something to the round that can't generally be found elsewhere, and I'd make the same argument for a Mediborg. If anything, the latter honestly make Med's job easier on low pop.

**Comment by Elijahrane** [comment]
I'm fine enabling warden and keeping medical cyborg but I don't want the psychiatrist role on low pop

**Comment by Pspritechologist** [comment]
Fair. Any comment on Reporter? I know that one was said to have really good RP, whereas Psych I can see being extremely niche

**Comment by Elijahrane** [comment]
reporter is actually good and you should consider replacing the psych office with that

**Comment by Pspritechologist** [comment]
That is precisely what I had been considering :P
I might use some of the unused Detective items, would look good in a proper reporter's office. What comes in a Detdrobe? If it's nothing too Sec related, it might be really good renamed

**Comment by Pspritechologist** [comment]
How does Reporter get categorized? Basic Service access for doors and what not? Needed items would be a camera, and that's about it, right? Going to include a handheld radio for sure, now that those work

**Pull request merged**
