### PR TITLE
Theft requires Escape

### PR DESCRIPTION
**Pull request by Vordenburg**
:cl:
- tweak: Syndicate theft objectives now require escaping on the shuttle.

### CODE REVIEW

**Comment by Elijahrane** [comment]
I'll have to think back to how SS13 solved this because escaping being a discrete objective when several others imply it is kind of weird

**Comment by ZeroDayDaemon** [comment]
Not sure this should be necessary, I mean staying behind could still imply an alternate escape or a syndicate being picked up post round.

**Comment by Qulibly** [comment]
What if someone escapes on say a shuttle or even shittle?

**Comment by Vordenburg** [comment]
@Elijahrane What is your conclusion?

**Pull request closed without merging**
