### PR TITLE
Minor edits

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Arena Update:

I noticed in the last round I observed the edits I pushed through earlier in the day were not there. Perhaps they were accidentally displaced by the other map edits later in the day.  This edit retains all previous edits,  (Salvage hotfix, removal of uncels, and vendor stock entity replacement.) It also replaces some televisions that were accidentally just the frames before and makes some slight adjustments to the arena making it a little more accessible to enter/exit as well as a few other qol adjustments based on my observations over the day.

### CODE REVIEW

**Comment by Elijahrane** [comment]
was the round you were observing before or after the last publish?

**Comment by IamVelcroboy** [comment]
It was the last round just before ass day ended.

**Comment by IamVelcroboy** [comment]
ok what failed?

**Comment by Elijahrane** [comment]
unrelated failure. did you actually change anything since last update? the reason you didn't see it is that the server didn't restart

**Comment by IamVelcroboy** [comment]
This update is different than the first one. It includes all the edits from earlier, plus the new ones mentioned above

**Pull request merged**
