### PR TITLE
Fix ClothingOuterHardsuitJuggernautReverseEngineered

### PR DESCRIPTION
**Pull request by VigersRay**
## About the PR 

I was tired of the error in the logs that the sprite of the included flashlight was not found and I decided to fix it.

**Media**

image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: VigersRay
- fix: Fix JuggernautReverseEngineered

### CODE REVIEW

**Comment by Vordenburg** [comment]
I had another look because I didn't think the cybersun juggernaut suit had a light, and it doesn't. What errors are you even seeing? The regular juggernaut suit and the reverse engineered one look fine to me.

**Comment by Vordenburg** [comment]
I looked one more time, and even the upstream juggernaut suit helmet does not have a light. Did you add a light to them somehow?

**Comment by VigersRay** [comment]
> I looked one more time, and even the upstream juggernaut suit helmet does not have a light. Did you add a light to them somehow?

oh, I forgot that I use Corvax sprites...

**Comment by Vordenburg** [comment]
Closing as this does not apply to this repository.

**Pull request closed without merging**
