### PR TITLE
Prevent admins from bypassing spawning permissions using brief

### PR DESCRIPTION
**Pull request by DebugOk**
## About the PR 
Cherry picked directly from Delta as is.

Changes the permission on brief to spawn, since the entity field doesn't check if the entity you're trying to spawn is actually a mob or not. Also adds rbrief on the old permission since it is a useful tool for trial admins and such.

### CODE REVIEW

**Comment by DebugOk** [comment]
The main issue with brief was that while it does only suggest prototypes starting with "mob" for autocompletion, its never actually checked. Meaning it'd happily spawn any prototype provided, and since its on the "admin" permission and not "spawn" it means you could bypass not having spawning abilities rather easily

**Review by Elijahrane — COMMENTED** [review]
actual code looks OK, although it's dawned on me again how the comp and command use weird naming that's not intuitive

**Comment by DebugOk** [comment]
> actual code looks OK, although it's dawned on me again how the comp and command use weird naming that's not intuitive

If it needs to be renamed, I can make that happen

**Comment by Elijahrane** [comment]
Yeah, a better name is all I'm asking

**Comment by Pspritechologist** [comment]
@DEATHB4DEFEAT 
The permissions were already fixed on Parkstation, and the naming is something I've spoken to Death about before.

**Comment by DebugOk** [comment]
Oh right I totally forgor about this

**Comment by Vordenburg** [comment]
I'd rather just extract this entire thing as-is, re: `Brief` and remove it from the codebase.

Why is it invading GhostSystem in such a specific way? Why does it have an inscrutable name? Admin commands are the sort of thing that everyone can benefit from unless they deal with some very specific system (hence why it should be offered to SS14 if it's useful). The general concept as I understand it is to turn an admin into a specific mob. There's already tools to do that. If the problem is character appearance, clothing, then there's the mirror and an admin can already spawn clothing.

Can anyone justify why this system must continue its existence here? It's very narrow in scope.

**Comment by Elijahrane** [comment]
> Can anyone justify why this system must continue its existence here? It's very narrow in scope.

It could get replaced with a functionality to load a human character profile onto a mob, something the mirror cannot do completely with stuff like sex. That's the only relevant part and the command to load a profile would be much cleaner anyway

**Comment by DebugOk** [comment]
> > Can anyone justify why this system must continue its existence here? It's very narrow in scope.
> 
> It could get replaced with a functionality to load a human character profile onto a mob, something the mirror cannot do completely with stuff like sex. That's the only relevant part and the command to load a profile would be much cleaner anyway

I already have code written for this on delta that does exactly this.

The only reason brief is handy is because admins without spawn have no other way of spawning in a character (on Nyano code, at least).

**Comment by Pspritechologist** [comment]
The usefulness of Brief has proven to be mostly speed- in a situation where you need to get a CentCom officer in fast, or when you quickly need to react to a situation with a specific character, it's *much* faster than spawning a mob, adding the clothing, changing the name, taking control, and then finally being ready to interact. Just an extremely convenient collection of actions, really. Certainly not vital for everyone, but I've found it to be extremely useful.
I can't argue for the specific coding of it, as I'm not intimately familiar with it.

**Comment by Vordenburg** [comment]
> (on Nyano code, at least).

You're saying that this is an aspect of this codebase and not representative of SS14 as a whole?

**Comment by DebugOk** [comment]
> > (on Nyano code, at least).
> 
> You're saying that this is an aspect of this codebase and not representative of SS14 as a whole?
> 

I'm not familiar with wizdens admin tools, and can't be bothered to check if they implemented something like it

**Pull request closed without merging**
