### PR TITLE
Fix Glacier & Nukie planet.

### PR DESCRIPTION
**Pull request by Vordenburg**
## About the PR 

This is a mix of my upstream PR
https://github.com/space-wizards/space-station-14/pull/12683 and cherry-picked https://github.com/space-wizards/space-station-14/pull/12650. Together, this should allow Glacier and the Nukie planet to load again with atmosphere and parallax. An explanation is on the upstream PR.

**Screenshots**

**Changelog**

:cl:
- fix: Glacier station has been placed back into the atmosphere.

### CODE REVIEW

**Comment by Elijahrane** [comment]
seems to fail tests, hmmm

**Comment by Elijahrane** [comment]
i might try this when i merge upstream tomorrow because it might depend on some other stuff

**Comment by Vordenburg** [comment]
That's quite possible. All tests passed on upstream. Weird.

**Comment by Elijahrane** [comment]
uhhh i'll wait and see what upstream is doing, the glacier update isn't even done yet

**Comment by Elijahrane** [comment]
i merged upstream, they have some planetmos stuff now, see if that is even needed

**Comment by Elijahrane** [comment]
i've merged upstream, see if glacier can be fixed now

**Comment by Vordenburg** [comment]
The saved map prototype is still being overwritten at this stage. We need https://github.com/space-wizards/RobustToolbox/pull/3511 or maybe https://github.com/space-wizards/RobustToolbox/pull/3516 due to https://github.com/space-wizards/RobustToolbox/issues/3523.

https://github.com/space-wizards/space-station-14/pull/12696 is also worth noting.

**Pull request closed without merging**
