### PR TITLE
Donator system

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
# About

I'm doing this since Rane didn't finish https://github.com/Nyanotrasen/Nyanotrasen/pull/1237 and said I could.
Make the rest of this description later

# TODO

- [x] Model/Migrations
- [x] Commands (add/remove/get)
- [x] Expiration date
- [ ] Donator OOC color
- [x] Donator soft cap ignore

Parkstation (here so I remember)

- [ ] Donator-only loadout items
- [ ] Custom cosmetic item to put in the loadout items tab

Random Rane Things (joke)

- [ ] God mode wallhacks esp aimbot
- [ ] 150% moves peed increase

<details><summary><h1>Media</h1></summary>
<p>

image

image

image

</p>
</details> 

# Changelog

:cl:
- add: Donators get their own OOC color.
- add: Donators can ignore the server's soft cap, similar to admins.

### CODE REVIEW

**Comment by Vordenburg** [comment]
This certainly seems like functionality that upstream will implement at some point. Have you tried there first?

**Comment by Elijahrane** [comment]
> This certainly seems like functionality that upstream will implement at some point. Have you tried there first?

this tbh, although if you want you can get some reviews here first

move everything out into a normal namespace / folder, assume this will be an upstream PR

**Comment by Vordenburg** [comment]
Are you coming back to this?

**Comment by DEATHB4DEFEAT** [comment]
> Are you coming back to this?

yeah

**Comment by Vordenburg** [comment]
It'd be best to make a PR on SS14 for this.

**Pull request closed without merging**
