### PR TITLE
Expand mail.

### PR DESCRIPTION
**Pull request by Vordenburg**
## About the PR 

This PR introduces:

- structural organization, more configuration, even unit tests.
- fragile mail, which can be detected automatically based on some simple criteria, or a delivery can be marked as fragile no matter what.
- priority mail, which has to be delivered under a certain time limit, or the station is penalized.
- priority mail and fragile mail both have configurable bonuses & maluses to their bounty & penalty, respectively.
- job icon stamps on each mail, what I think will be a wonderful addition for people who play mail carrier and have to deal with many deliveries.
- mail changes appearance to look grungy if it takes damage.
- mail transfers damage to its contents.
- fragile mail penalizes the station if it's damaged.
- mail takes damage on falling, like glass and other fragile items.
- MailItem prototypes that were in YML that weren't in the list of spawnable mail have been added in, like the wizard cosplay mail.

Some things I still want to have a go at:

- [x] redesign the mail carrier uniform.
- [x] add a jumpskirt variant.
- [x] add Department/Role-specific mail.
- [x] add emag interactions.
- [x] add more delivery possibilities.
- [x] tweak weighted prototype values.
- [x] remove debug messages when everything's done.

This PR could use some feedback on the values for bonuses/maluses and how long priority mail should be in the clear.

**Screenshots**

image

image

image

image

**Changelog**

:cl: Vordenburg
- add: Added job icon stamps for mail to make it easier to sort.
- add: Added fragile mail. If you break it, you're in trouble.
- add: Added priority mail. Get it delivered on time or face a penalty.
- add: Added mail for specific jobs and departments.
- add: Added a lot of new possible deliveries you can receive.
- add: Mail will now change appearance when damaged.
- add: Damage to mail will harm its contents too.
- fix: Mail parcels can be emagged open now.
- tweak: Mail teleporters have a limit on undelivered mail now to prevent it from piling up.
- add: One of the new Arachne tailors made a jumpskirt variant of the mailman uniform!
- tweak: That same tailor redesigned the standard mailman uniform and hat.

:cl: spessCarp
- add: Wrote several letters that can be received in the mail.

### CODE REVIEW

**Comment by Vordenburg** [comment]
@Elijahrane Ready for review.

**Review by Elijahrane — APPROVED** [review]

**Comment by Elijahrane** [comment]
read the whole thing, didn't notice any mistakes, if anything pops up we can patch it real quick

**Comment by Vordenburg** [comment]
Looks like the automatic changelog isn't smart enough to detect the second contributor. Can that be fixed manually?

**Comment by Elijahrane** [comment]
yeah

**Comment by ZeroDayDaemon** [comment]
> Looks like the automatic changelog isn't smart enough to detect the second contributor. Can that be fixed manually?

we can manually add it, but normally you'd just put a comma "," and then their name and add their changes to the same block

IE:

CL Joe, Jim

Change bla bla bla

**Pull request merged**
