### PR TITLE
Adds Arena Evac shuttle

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Changelog:
- Adds Uncle Charlie's Luxury Boat, an Evac vessel for Arena Station.

:cl: Velcroboy, Old Dance Jacket, Colin-Tel
- add: Added Uncle Charlie's Luxury Boat!

### CODE REVIEW

**Comment by Vordenburg** [comment]
Without context, the way the player-facing changelog reads makes it sound like a new ship is available from the shipyard dock console. If all this does is change the evac shuttle for Arena, is it really necessary for a changelog entry?

**Comment by IamVelcroboy** [comment]
> Without context, the way the player-facing changelog reads makes it sound like a new ship is available from the shipyard dock console. If all this does is change the evac shuttle for Arena, is it really necessary for a changelog entry?

It's Uncle Charlie's Luxury Boat. Evac in style

**Comment by IamVelcroboy** [comment]
I don't know though. I think it's pretty cool and will be noticed when it shows up. But I'm not at my pc anymore for the night to change anything

**Comment by OldDanceJacket** [comment]
> Without context, the way the player-facing changelog reads makes it sound like a new ship is available from the shipyard dock console. If all this does is change the evac shuttle for Arena, is it really necessary for a changelog entry?

Yeah, I agree, on the other, this is kinda a sick af evac so

**Pull request merged**
