### PR TITLE
new lobby song

### PR DESCRIPTION
**Pull request by Elijahrane**
:cl: Rane
- add: Added a new lobby song.

### CODE REVIEW

**Comment by DebugOk** [comment]
What'd atomic amnesia do to deserve getting wiped

**Comment by Elijahrane** [comment]
> What'd atomic amnesia do to deserve getting wiped

soulless

**Comment by DebugOk** [comment]
Sad times, I liked it

**Comment by Elijahrane** [comment]
we need space for when there's lobby song rotation so we can add the classics like robocop.mp3 that are a bit too short

**Pull request merged**
