### PR TITLE
Robot tool powercell

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR 
- Adds a special robot/borg battery cell (PowerCellRobotTool) that inherit from PowerMediumCell with a recharge rate of 4.
- Changes every robot tools that require cell to use the PowerCellRobotTool (Health Analyser, Crew Monitor)
- Add special robot version of the Engineering Holographic Projector.
- Make every robot tool inherit from their original tool to avoid future issues, thanks past me for not doing that
  - Technically fixes the medical robot health analyser sprite being bugged.

**Changelog**

:cl:
- fix: Fixed robots holoprojector running out of charges.

### CODE REVIEW

**Comment by Vordenburg** [comment]
The test failure is valid. Check under `ReverseEngineeringTest.cs` for how I fixed this for the regular HandheldCrewMonitor.

**Comment by Vordenburg** [comment]
Tests can be run locally.

**Comment by FluffiestFloof** [comment]
My laziness is beyond human understanding but yeah I should probably do that

**Comment by Vordenburg** [comment]
`dotnet test -e COMPlus_gcServer=1`

**Pull request merged**
