### PR TITLE
Bomber jak

### PR DESCRIPTION
**Pull request by PowerfulAtom111**
## About the PR 

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added a recipe for the bomber jacket in the uniform printer.
- add: Added a soyjak plushie which can be found in the plushie crate.

proof-my-PR-works

### CODE REVIEW

**Comment by PowerfulAtom111** [comment]
Anything wrong with the PR?

**Comment by Vordenburg** [comment]
This PR tries to do two completely separate things at once, at a glance.

Looking deeper, you have added a new death commando name "Chad Thundercock" ?
And you removed the mention of "WW2" from the bomber jacket.
Then there's the issue where you duplicated "plushie_atmosian" into the toys meta.json

What is going on here?

**Comment by PowerfulAtom111** [comment]
>This PR tries to do two completely separate things at once, at a glance.

I had 2 ideas, didn't wanna make 2 PRs. So I combined them and it works.

>Looking deeper, you have added a new death commando name "Chad Thundercock" ?

I was browsing through the files and saw the names.yml for the deathsquad commandos. The names reminded me of the name "Chad Thundercock," which I know is unrelated to the PR, but I thought it was a funny reference.

>And you removed the mention of "WW2" from the bomber jacket.

I removed it because bomber jackets aren't exclusive to WW2.

>Then there's the issue where you duplicated "plushie_atmosian" into the toys meta.json

I had to copy+paste the stuff from Nyano:master into my local repo because I fucked up the toys.yml so badly I had to remake the file. Unfortunately, this resulted in the "duplication" of the atmosian plushie. If my memory serves, the one you see in green is the only thing referring to the atmosian plushie. I know it works, too, because there's only one type of atmosian plushie in my testing with it.

>What is going on here?

What WAS going on was my attempt to add a bomber jacket recipient and a soyjak plushie in one PR, because it's quicker that way. It's done and tested, now. All it needs is to be merged (so does the chemistry guide but that's unrelated).

**Comment by Vordenburg** [comment]
If we're going to touch the uniform printer, then all the missing coats and standard uniforms should be added. That would be best. Right now, most winter coats are missing. There are a couple regular uniforms missing. The atmos tech one comes to mind.

**Comment by PowerfulAtom111** [comment]
Give me a list of all the missing coats, and I can get them added if need be. But otherwise, I'd rather get the bomber jacket in and then make another PR for the rest of the missing coats later.

**Comment by PowerfulAtom111** [comment]
After... "careful" discussion with a friend, I'm gonna split this into another PR, with this being the soyjak plushie. The other will have the bomber jacket PLUS any other missing jackets, alongside renaming the uniform fabricator to "mechanical loom" to better define what the machine does.

**Comment by PowerfulAtom111** [comment]
After more thinking, I'm just gonna go nuclear with this PR and start fresh over with 2 new PRs.

**Pull request closed without merging**
