### PR TITLE
Makes switches directional

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Changelog:

-Changes 360 accessibility to wall-mounted switches to 180, making them directional.

Discussed with ODJ and Collin. We are all in agreement this will make things better.

### CODE REVIEW

**Comment by Vordenburg** [comment]
Will our maps support this change? Switches appear to be centered, so it's hard to see when they're rotated.

**Comment by IamVelcroboy** [comment]
You can visually tell when you are mapping them as they are slightly rectangular. So, mappers would need an alert to double check them. But, it shouldn't be a huge hassle.

**Comment by IamVelcroboy** [comment]
Looking close, you can tell which side is "up" by the silver top and bright green switch
image

**Comment by Vordenburg** [comment]
I tested this locally and it seemed to work. If our mappers can take a look over their buttons, I don't see any issue with merging this. I think it might be useful if the sprite had an offset (easily doable through the YAML), so it is pointing more in the direction it faces, or alternatively had a different sprite entirely.

**Comment by IamVelcroboy** [comment]
More than this? 
image

**Comment by Vordenburg** [comment]
Yes, something like that. I'd defer to the mappers as to what they think is aesthetically pleasing, but all four directions shouldn't be able to easily stack in the same space. Maybe it could even be setup so the north/south or east/west buttons can be overlaid seamlessly if there was a need for that.

**Comment by Vordenburg** [comment]
Having discussed this with Rane, the better way to do this would be with a new entity.

The visual change should be fine for now to get mappers on board with aligning where their buttons go if they need to orient them, but I will probably revert that once we get a proper directional button entity. Upgrading all the buttons would be as simple as a find & replace.

Upstream may be interested in this as well, so I recommend giving that a try too.

**Pull request closed without merging**
