### PR TITLE
Adds defibrillator to cargo catalog

### PR DESCRIPTION
**Pull request by PPooch**
## About the PR 

Touched the defibrillator crate to put a defib + a spare medium cell in (the defib prototype spawns with a medium cell inside it too). Set the cost in cargo for $5000. Defibs appraise for $100 without cell, $208 with cell, and the cell itself is $108. Thoughts on the price?
Upstream push from https://github.com/DeltaV-Station/Delta-v/pull/22
**Media**
image

**Changelog**

:cl: Pooch
- tweak: Defibrillators can be ordered from Cargo.

### CODE REVIEW

**Comment by Elijahrane** [comment]
I think defibs might have been deliberately not included in cargo ordering. They might be supposed to be somewhat limited.

**Comment by Vordenburg** [comment]
I'm in favor of limiting defibrillators.

**Comment by Elijahrane** [comment]
Still unsure how to feel. Could maybe do a quick survey on how defibs are acquirable in various SS13 codebases with them.

**Comment by PrPleGoo** [comment]
shouldn't science be able to print these no matter how you spin it? adding it to cargo with a 95% profit margin sounds very nanotrasen

**Comment by Vordenburg** [comment]
Closing, as defibrillators are now printable on the medical techfab.

**Pull request closed without merging**
