### PR TITLE
Adds Mapping command "tilewindows"

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Changelog:

- Adds tool for placing reinforced tiles under every window.

A simple tool for mappers to use to ensure consistency across an entire map.  

https://user-images.githubusercontent.com/107660393/231829574-c68f0a05-8c16-4439-bc85-e789c0b8a57f.mp4

### CODE REVIEW

**Comment by Elijahrane** [comment]
are windows supposed to have reinforced tiling, or underplating...?

**Comment by IamVelcroboy** [comment]
> are windows supposed to have reinforced tiling, or underplating...?

Last time I mapped with @OldDanceJacket we decided on reinforced. I can see if he'll confirm that though.

**Comment by OldDanceJacket** [comment]
Yes this is the agreed upon visual design to have under windows and would be good practice for other mappers to just easily run a command for it.

**Comment by Vordenburg** [comment]
This is really cool. The more we can automate the tedium of a mapper, the better.

**Pull request merged**
