### PR TITLE
make ringtone and uplink code 6 notes long

### PR DESCRIPTION
**Pull request by BasedUser**
## About the PR
literally just makes uplinks 2 notes longer
oh and also notes can include sharps now but nobody uses ringtones anyway so i don't think they'd notice

this PR resolves the issue of skids being able to bruteforce through 625 (5\*\*4) combinations in 5 minutes, now they'll have to bruteforce through 3M (12\*\*6) in 16 days (unless they bot the attack in which case we wait for packet flood bans) or literally ask the traitor involved for their code

**Media**
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: router
- tweak: Ringtones now have 2 more notes you can play around with, and also can generate with non-pentatonic notes.
- fix: The Syndicate has taken advantage of this hardware expansion, making brute-force attacks on their uplinks unfeasible.

### CODE REVIEW

**Comment by Elijahrane** [comment]
Is the introduction of non-pentatonic notes necessary to stop brute forcing?

**Comment by deltanedas** [comment]
its the difference between 15625 and 1000000

**Comment by DebugOk** [comment]
> its the difference between 15625 and 1000000

So it goes from impossible to impossible²

**Comment by BasedUser** [comment]
> Is the introduction of non-pentatonic notes necessary to stop brute forcing?

to uplinks? yes, but not necessarily to ringtones as a whole, i'll have a look at how i could split that

> So it goes from impossible to impossible²

it goes from bruteforceable to "you need a hacked client and will likely get packetbanned if you try"

**Comment by BasedUser** [comment]
this will take more than an hour

**Comment by Vordenburg** [comment]
Is there a reason that this has not been sent upstream?

**Comment by BasedUser** [comment]
> Is there a reason that this has not been sent upstream?

Mostly personal preference (due to an unreasonable PR quality barrier). Upstream can adapt this PR or a variant anytime regardless.

**Comment by Vordenburg** [comment]
> Upstream can adapt this PR or a variant anytime regardless.

Every divergent change to the engine increases maintenance load, thus the effort of maintenance must be justified. I.e. it is entirely possible and likely that this system gets rewritten at some point, then this PR's changes must be accounted for by whoever is going to merge the future change from upstream.

I don't see any reason why upstream wouldn't also want to prevent brute-force measures by players.

**Comment by BasedUser** [comment]
@deltanedas thoughts on upstream bump?

**Comment by deltanedas** [comment]
i wouldnt mind it

**Comment by Vordenburg** [comment]
Closed, as is relevant to upstream.

**Pull request closed without merging**
