### PR TITLE
tweaked the chemistry guide so that it may work.

### PR DESCRIPTION
**Pull request by PowerfulAtom111**
Changelog
- add: added a possibly working chemistry guide

### CODE REVIEW

**Comment by PowerfulAtom111** [comment]
i compared working guides to mine and made mine look more like those.

**Comment by Elijahrane** [comment]
it's poor form to make duplicate prs usually

this also is lacking the changes I made to the last one to actually show up in the guidebook

**Comment by PowerfulAtom111** [comment]
FUCK

**Comment by PowerfulAtom111** [comment]
waht changes did you make

**Comment by Elijahrane** [comment]
go fix the original pr please

**Pull request closed without merging**
