### PR TITLE
Map Edits

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Changelog:

Updates Tortuga to be "Arrivals" ready.

### CODE REVIEW

**Comment by Elijahrane** [comment]
What sort of changes did you make?

**Comment by IamVelcroboy** [comment]
> What sort of changes did you make?

I rearranged the arrivals area to accommodate the arrivals shuttle when it's merged here. See Discord for a screenshot.

**Comment by Elijahrane** [comment]
will it break anything if arrivals is not merged / disabled?

**Comment by IamVelcroboy** [comment]
> will it break anything if arrivals is not merged / disabled?
No. It's purely cosmetic. I can add a psuedo-shuttle back in later if arrivals isn't added or whatever.

**Pull request merged**
