### PR TITLE
Add Tier One Parts to Engineering Techfab

### PR DESCRIPTION
**Pull request by Tryded**
Adds Capacitors, Matter-bins, and Micro-Manipulators to engineering Techfab static recipes.

## About the PR 
Adds Capacitors, Matter-bins, and Micro-Manipulators to engineering Techfab static recipes, due to no research adding said parts.
**Media**

PartPrintingReal1
PartPrintingReal2

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added the ability for engineering techfab to print tier one machine parts without research.

### CODE REVIEW

**Review by Vordenburg — CHANGES_REQUESTED** [review]
Remove the basic parts from the dynamic recipes, then place them at the end of staticRecipes similar to how they are structured in dynamic, with surrounding comment lines.

**Comment by Tryded** [comment]
It has been fixed

**Review by Vordenburg — APPROVED** [review]

**Comment by Tryded** [comment]
Uh, is the test suppose to fail?

**Comment by Vordenburg** [comment]
Github test timed out. It's irrelevant.

**Comment by Tryded** [comment]
So, what do we do now?

**Comment by Vordenburg** [comment]
This PR's fine. I'll look into merging it and others tomorrow.

**Pull request merged**
