### PR TITLE
Cherrypick 2023 01 01

### PR DESCRIPTION
**Pull request by Vordenburg**
The Popup occlusion temp fix has been included. If no bugs crop up related to that, we should be good to start removing the manual occlusion checks.

### CODE REVIEW

**Comment by Elijahrane** [comment]
Should make a note to give our headsets default channels. I can open an issue if you don't feel like doing it this PR

**Comment by Elijahrane** [comment]
replace supply with binary to fix that yaml linter failure

**Comment by Vordenburg** [comment]
Good catch. I caught all the changes related to default channels on the headsets that already exist, but I forgot about the custom headsets we have (despite just yesterday doing a PR related to that.)

**Comment by Vordenburg** [comment]
Easy enough to fix here.

**Pull request merged**
