### PR TITLE
Sweater

### PR DESCRIPTION
**Pull request by Just-a-Unity-Dev**
## About the PR 
Requires #301 (I love paper). I don't know how to put it in the maint loot pool so cry about it

### CODE REVIEW

**Comment by Elijahrane** [comment]
test failure

**Comment by Just-a-Unity-Dev** [comment]
guh

**Comment by Just-a-Unity-Dev** [comment]
> test failure

works on my machine and it's the RSI validator only

**Comment by Elijahrane** [comment]
> > test failure
> 
> works on my machine and it's the RSI validator only

are you gonna make me fix it

**Comment by Just-a-Unity-Dev** [comment]
> > > test failure
> > 
> > 
> > works on my machine and it's the RSI validator only
> 
> are you gonna make me fix it

no

**Pull request merged**
