### PR TITLE
Add Chef's Guide and Cookbook into Guidebook

### PR DESCRIPTION
**Pull request by Torun-S**
## About the PR

This is going to add a guide for the Chef and the full Cookbook into the Guidebook. It might have fallen a bit out of date, but for now, the framework is laid in, 99% of recipes are in, the formatting is polished out as much as the current CSS of the Guidebook allows. This means it's ready for everyone to read and enjoy, and a stepping stone for my further cooking shenanigans as well as anyone else's... If they manage to not get lost in the .xml.

- [x] Enumerate recipes
- [x] Sort them into categories
- [x] Punch them in
- [x] Sort out
    - [x] Recognize patterns among recipes and merge somehow
    - [x] Merge some categories above as feasible
- [x] Debug
- [x] Proofread

**Media**
image
image

**Changelog**

:cl: Torun
- add: Added Chef's Guide and the full Cookbook into the Guidebook.

### CODE REVIEW

**Comment by Torun-S** [comment]
I finally managed to understand the Cooking system and foods to some extent, so I can begin putting the recipes in proper.

During that, I noticed some recipes that can be made to have much more sense and foods that don't have recipes, but don't miss much from having one with a new item here and new recipe there, so another PR can be expected on that.

Note: There are currently 105 microwave recipes and a few more mixing recipes, that's notwithstanding all the interactions with a grinder and slicing, where most are not going to be mentioned and considered common sense enough (I mean, grinding wheat into flour doesn't need its own recipe does it)?

**Comment by Torun-S** [comment]
If the CI test says something about Cookbook failing to parse, don't believe it, it often does a false-positive.

@Elijahrane Ready to merge at last!

**Comment by Elijahrane** [comment]
can we get GuideHelp on the microwave etc

**Comment by Torun-S** [comment]
Done!

**Comment by Elijahrane** [comment]
works on my machine

**Pull request merged**
