### PR TITLE
Updates ChefVend inventory w/ Monkey Cubes

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Changelog:

-Adds monkey cube box to ChefVend
-Adjusts restock price accordingly

(sorry, I meant to update with the chefvend texture at the same time.)

### CODE REVIEW

**Comment by Vordenburg** [comment]
It's a little out of place for the Chef to start with monkey cubes. As with any job, they're not in need of every single niche thing they can possibly interact with right at the start, and it gives them something to ask cargo to order if they really want it.

**Comment by IamVelcroboy** [comment]
The reason I added them, is because the chef closet, which we could ideally phase out, had 2 boxes of them.

**Comment by IamVelcroboy** [comment]
fwiw, I agree they don't need to start with everything. Just wanted you to know they were previously starting with them. Albeit, with less of the other items. So, I can see this as a fair trade.

**Comment by OldDanceJacket** [comment]
Doesn't the ChefVend you added have meat in them already?

**Comment by IamVelcroboy** [comment]
Yes, 6 pieces. Not sure how much you get from a monkey without looking but I know there are 6 monkeys in a box and there were 2 monkeys in the chef closet. So, I'm sure it's already significantly lower than what they had.

**Pull request closed without merging**
