### PR TITLE
Restore crew's clothing on spawn

### PR DESCRIPTION
**Pull request by jicksaw**
## About the PR 
A change in the engine, and a Nyano specific change caused players to spawn without their clothes being applied (nude).

Change in the engine: https://github.com/space-wizards/RobustToolbox/pull/3866
Nyano commit: https://github.com/Nyanotrasen/Nyanotrasen/pull/1103

I have no idea what I'm doing; I haven't looked at game state or event flow before. But this change seems to fix it. No idea how to test the desync errors or whatever the original change was meant to fix.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: jick
- fix: Crew board with their clothes on

### CODE REVIEW

**Comment by Vordenburg** [comment]
That commit was originally a fix for https://github.com/Nyanotrasen/Nyanotrasen/pull/1093 so if your PR here brings us to parity with upstream content and the engine fix is good, everything should be solid.

**Comment by jicksaw** [comment]
This restores the bug with blindfold curing permanent blindness >.<

**Comment by Vordenburg** [comment]
I was just testing this locally and saw that.

**Comment by Vordenburg** [comment]
I think it might be better to delete the conditions entirely, since they're not doing what was intended, and upstream content doesn't check either.

**Comment by jicksaw** [comment]
Removed the checks.

When I tested the code:
```csharp
    private void OnEntInserted(EntityUid uid, InventoryComponent component, EntInsertedIntoContainerMessage args)
    {
        if(!TryGetSlot(uid, args.Container.ID, out var slotDef, inventory: component))
            return;

        if (!_gameTiming.IsFirstTimePredicted && !_gameTiming.ApplyingState)
            return;

        Logger.Error("Got OnEntInserted for " + ToPrettyString(args.Entity) + " in slot " + slotDef.DisplayName + " isFirstTime: " + _gameTiming.IsFirstTimePredicted + " ApplyingState: " + _gameTiming.ApplyingState + " InPrediction: " + _gameTiming.InPrediction);

        var equippedEvent = new DidEquipEvent(uid, args.Entity, slotDef);
        RaiseLocalEvent(uid, equippedEvent, true);

        var gotEquippedEvent = new GotEquippedEvent(uid, args.Entity, slotDef);
        RaiseLocalEvent(args.Entity, gotEquippedEvent, true);
    }
```

I got this output from when I switched from sunglasses -> blindfold -> sunglasses:

```
[ERRO] root: Got OnEntInserted for blindfold (1633, ClothingEyesBlindfold) in slot Eyes isFirstTime: True ApplyingState: False InPrediction: True
[ERRO] root: Got OnEntInserted for sun glasses (1611, ClothingEyesGlassesSunglasses) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for sun glasses (1611, ClothingEyesGlassesSunglasses) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for sun glasses (1611, ClothingEyesGlassesSunglasses) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for sun glasses (1611, ClothingEyesGlassesSunglasses) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for sun glasses (1611, ClothingEyesGlassesSunglasses) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for sun glasses (1611, ClothingEyesGlassesSunglasses) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for sun glasses (1611, ClothingEyesGlassesSunglasses) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for sun glasses (1611, ClothingEyesGlassesSunglasses) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for sun glasses (1611, ClothingEyesGlassesSunglasses) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for sun glasses (1611, ClothingEyesGlassesSunglasses) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for sun glasses (1611, ClothingEyesGlassesSunglasses) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for blindfold (1633, ClothingEyesBlindfold) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for sun glasses (1611, ClothingEyesGlassesSunglasses) in slot Eyes isFirstTime: True ApplyingState: False InPrediction: True
[ERRO] root: Got OnEntInserted for blindfold (1633, ClothingEyesBlindfold) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for blindfold (1633, ClothingEyesBlindfold) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for blindfold (1633, ClothingEyesBlindfold) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for blindfold (1633, ClothingEyesBlindfold) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for blindfold (1633, ClothingEyesBlindfold) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for blindfold (1633, ClothingEyesBlindfold) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for blindfold (1633, ClothingEyesBlindfold) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for blindfold (1633, ClothingEyesBlindfold) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for blindfold (1633, ClothingEyesBlindfold) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for blindfold (1633, ClothingEyesBlindfold) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for blindfold (1633, ClothingEyesBlindfold) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
[ERRO] root: Got OnEntInserted for sun glasses (1611, ClothingEyesGlassesSunglasses) in slot Eyes isFirstTime: False ApplyingState: True InPrediction: False
```

To me it looks like the server is sending 11 events with the old item before sending the event with the correct item.

**Pull request merged**
