### PR TITLE
Guidebook Update

### PR DESCRIPTION
**Pull request by OCOtheOmega**
## About the PR

Update guidebook, remove duplication, update old, add new.

**Media**
изображение

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:

- add: New guidebooks!

### CODE REVIEW

**Comment by Vordenburg** [comment]
I had planned on this eventually.

I see only one commit here though. Most of the issue was due to skipped commits or partial cherry-picks due to the guidebook folder being re-arranged by previous commits merged not under my tenure. Given the depth of everything involved, I would have preferred to see multiple commits, and this may take a significant amount of time to review, given the lack of revision documentation.

Ultimately I think it would be better to revert if possible the commits that altered the guidebook folder on this repo, or reduce it to a state where it is compatible enough with SS14, that I can go back and re-pick what was missing. This would be something I would do.

This is one of those things that should've been raised as an issue where I could intervene and comment on it before anyone went out and did unnecessary work.

Can you at least describe what you did here?

**Comment by OCOtheOmega** [comment]
I as a person who deals with localization realized that a huge part of the files are duplicated, and thrown out of the necessary folders, some of the guides are just outdated because of what I also updated them, as well as I changed the structure of categories in the guide book, making it closer to the one that is now at wizard. (like files, folders names)

**Comment by Vordenburg** [comment]
Okay, I did a quick skim of the files you touched. This PR does not add any of the GuideHelp components to game entities that have surely been missed. I think it would be best if I handle this myself by going back through and picking up the commits that have been missed after re-organizing the directory layout.

This issue is on my radar, at least.

**Comment by OCOtheOmega** [comment]
Well, I myself noticed that some of the files for guidebooks are missing, a little later I wanted to write it separately and refer to the fact that this pr should be merged after the things from upstream will be added.

**Comment by OCOtheOmega** [comment]
Close due [Vordenburg](https://github.com/Vordenburg) make new pr with guidebook update.

**Pull request closed without merging**
