### PR TITLE
Get rid of mapped corpium on a salvage wreck

### PR DESCRIPTION
**Pull request by DebugOk**
## About the PR
This PR removed the corpium from the roffle waffles in the atlas medical wreck, and instead replaces it with lexorin. I feel like salvage techs eating weird waffels from space to turn into zombies is very lame and meta gamey.

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Elijahrane** [comment]
just delete the whole entity

**Comment by DebugOk** [comment]
I feel like it'd be more funny if someone tried eating it and just got poisoned instead, but removing it is an option as well

**Comment by IamVelcroboy** [comment]
Maybe players should be asking why are they eating food you found in a morgue on a salvage wreck?

**Comment by Elijahrane** [comment]
> Maybe players should be asking why are they eating food you found in a morgue on a salvage wreck?

because they know OOC it will turn them into a zombie and end the round

**Comment by Nousagi37** [comment]
This isn't a popular PR, got plenty of downvotes.

**Comment by Elijahrane** [comment]
ok well we're merging it

**Comment by Vordenburg** [comment]
I'm in favor of this PR.

**Review by Elijahrane — CHANGES_REQUESTED** [review]
ok to be clear, just delete the uid entry on this map for the waffles entirely so that they do not spawn

**Comment by DebugOk** [comment]
> ok to be clear, just delete the uid entry on this map for the waffles entirely so that they do not spawn

Sure thing, I'll do it in a few hours when I get off of work

**Comment by DebugOk** [comment]
Assuming I can safely just outright delete the entity from the yml without having to savemap it, that should do it

**Comment by DebugOk** [comment]
Guess not, I'll remap it properly

**Review by Elijahrane — APPROVED** [review]

**Pull request merged**
