### PR TITLE
Unmineable mountain rock

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Changelog:
- High yield mountain rock becomes unmineable
- Low Yield mountain rock has increased HP 150-300
- Loot pool for LY mountain rock is inverted so there's a higher chance of rare ore/lower chance of common ore(loot drop percentage stays the same)
-  Slightly retextures LY Mountain Rock for visual indication it is mineable 

Screenshot 2023-01-31 001605
Screenshot 2023-01-31 001559

### CODE REVIEW

**Comment by Elijahrane** [comment]
I've read the PR desc and the PR a few times and I don't get what the goal of these changes are. If you don't want people mining them why have a yield at all?

**Comment by IamVelcroboy** [comment]
Because they can still be blown up/blasted. They are not indestructible. Just un-mineable. Making them useful for maps like Glacier where we don't want people mining away structural rock walls

**Comment by Elijahrane** [comment]
> Because they can still be blown up/blasted. They are not indestructible. Just un-mineable. Making them useful for maps like Glacier where we don't want people mining away structural rock walls

yeah but as far as I can tell these protos are only used on glacier and arena, my question is why do either of them have a yield

**Comment by IamVelcroboy** [comment]
Likely, they will get used in salvage too. And potential future maps.

The low yield/high value mountain rock has double HP from asteroid rock, giving some extra variables for mining area's. The non-mineable variant would just have a yield for if/when it gets destroyed, it might still drop something.

**Comment by Elijahrane** [comment]
mmm, it sounds like you guys have a plan for this then

**Pull request merged**
