### PR TITLE
Changes the RE sprite.

### LINKED ISSUE #1636: Reverse engineering machine too tall
The extra visual space it occupies isn't used for much, and it's causing issues with draw depths because the upper half needs to be over mobs but the lower half needs to be under items (which is impossible to do both). The sprite could be shortened.

### PR DESCRIPTION
**Pull request by Hyenh**
## About the PR 
Changes the RE sprite for the purpose of fitting it into a 32x32 canvas. 

**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:Hyenh
- add: Added fun!
- remove: Removed fun!

### CODE REVIEW

**Comment by Vordenburg** [comment]
Good work.

**Comment by Vordenburg** [comment]
I think you'll need to remove the `offset: "0.0,0.5"` line from the `ReverseEngineeringMachine`'s sprite component for this to align properly.

**Comment by Hyenh** [comment]
> I think you'll need to remove the `offset: "0.0,0.5"` line from the `ReverseEngineeringMachine`'s sprite component for this to align properly.

Alright, I'll also be changing the palette too. This sprite is a bit old, but I found it worked well for a RE machine. Originally, it was for a drone machine.

**Comment by Hyenh** [comment]
image

**Comment by Vordenburg** [comment]
Looking nice. Let me know when you're ready to merge it.

**Comment by Hyenh** [comment]
> Looking nice. Let me know when you're ready to merge it.

I've settled everything here. Ready to merge.

**Pull request merged**
