### PR TITLE
Adds Rickenbacker

### PR DESCRIPTION
**Pull request by ZeroDayDaemon**
## About the PR 
Adds a new instrument and an antagonist variant of it for the musician uplink.
**Screenshots**

**Changelog**

:cl:
- add: Added a new musical instrument, as well as an antagonist variant for musicians
- tweak: Buffed kanabou

### CODE REVIEW

**Comment by Elijahrane** [comment]
why does this do more damage than the kanabou

**Comment by ZeroDayDaemon** [comment]
> 

It costs the same as the antag fire axe, without the fire, and does 1 more damage when wielded. Also does no structural damage

**Comment by Elijahrane** [comment]
maybe kanabou just hasn't kept up with the power creep

if you are adding another uplink melee could you fix it real quick

**Comment by ZeroDayDaemon** [comment]
okay

**Comment by ZeroDayDaemon** [comment]
kanabou does 22 base, +8 wielded

Do you want it to:

1. Do 20 base, +12 wielded
2. Do 22 Base, +10 wielded

**Comment by Elijahrane** [comment]
the latter probably, the decent single handed is a good niche

**Comment by ZeroDayDaemon** [comment]
FYI for future reference, the rickenbacker only having left inhands is a design choice

**Pull request merged**
