### PR TITLE
Update angle.yml

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR 

Completely overhauled Angle's medical department.

**Media**

Angle-0

**Changelog**

:cl:
- tweak: The Angle Rig's medical department has been completely overhauled.

### CODE REVIEW

**Comment by Colin-Tel** [comment]
one moment, don't merge

**Comment by Colin-Tel** [comment]
Fixed, it was missing a medical techfab.

**Comment by Colin-Tel** [comment]
shit nevermind it's not fixed, hang on again

**Comment by Plyushsune** [comment]
Is it cabbage certified?

**Pull request merged**
