### PR TITLE
Goats will eat kudzu

### PR DESCRIPTION
**Pull request by PrPleGoo**
Goats will run at kudzu and eat it.

### CODE REVIEW

**Comment by Elijahrane** [comment]
All of the folders need to be moved to Content.Server/Nyanotrasen, Resources/Nyanotrasen, etc.

**Comment by PrPleGoo** [comment]
What about the changes made to the prototypes?

**Comment by Elijahrane** [comment]
You can leave changes to existing prototypes in the prototype

**Comment by PrPleGoo** [comment]
There you go

**Review by Elijahrane — APPROVED** [review]
code seems good, I'll merge after I test in game

**Comment by Elijahrane** [comment]
https://user-images.githubusercontent.com/60792108/186963479-57214c66-3f0c-49ca-b578-75d11e747cee.mp4

Am I doing something wrong?

**Comment by PrPleGoo** [comment]
`NPCSystem.Initialize`
set the override to true

**Pull request merged**
