### PR TITLE
Categorizes alcohol, comments where recipe is missing

### PR DESCRIPTION
**Pull request by Humonitarian**
## About the PR

Categorizes alcohol by strength, changes some alcohol values, makes Gargleblaster actually blast gargles.
Adds a comment to every cocktail with no recipe yet.
PS: If you'd prefer I move this upstream, I can.

**Changelog**

:cl:
- tweak: Alcohol values tweaked

### CODE REVIEW

**Comment by ZeroDayDaemon** [comment]
https://github.com/space-wizards/space-station-14/pull/9410

**Comment by Humonitarian** [comment]
> [space-wizards/space-station-14#9410](https://github.com/space-wizards/space-station-14/pull/9410)

> textures with /tg/'s

:)

**Comment by ZeroDayDaemon** [comment]
> :)

Yes, just like nearly every other texture in the game

**Comment by Humonitarian** [comment]
> Yes, just like nearly every other texture in the game

Hey, you do you

I mean, I wouldn't pile texture swap PRs with feature reworks, but you do you

**Comment by ZeroDayDaemon** [comment]
> > Yes, just like nearly every other texture in the game
> 
> Hey, you do you
> 
> I mean, I wouldn't pile texture swap PRs with feature reworks, but you do you

bartending is a complete mess in terms of textures, it is absolutely best to just rip it all out and restart. as for doing it at the same time as the reagents, well, i need the textures to do the drinks and i need the drinks to use the textures

**Comment by Humonitarian** [comment]
> > > Yes, just like nearly every other texture in the game
> > 
> > 
> > Hey, you do you
> > I mean, I wouldn't pile texture swap PRs with feature reworks, but you do you
> 
> bartending is a complete mess in terms of textures, it is absolutely best to just rip it all out and restart. as for doing it at the same time as the reagents, well, i need the textures to do the drinks and i need the drinks to use the textures

Does ethanol remain unmodified?

**Pull request closed without merging**
