### PR TITLE
Adds Medipen boxes/crates

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Changelog:

- Adds medipen(emergency, anti-poison, space) boxes and crates
- Adds cargo order for crates

:cl: Velcroboy
- add: added medipen(emergency, anti-poison, space) boxes and crates

### CODE REVIEW

**Comment by Elijahrane** [comment]
these are a bit redundant with the first aid kit crates

**Comment by DebugOk** [comment]
Medipens are nice though, as its a quick and easy fix that might allow someone to survive long enough to see doctors instead of dying and having to be cloned

**Comment by Elijahrane** [comment]
> Medipens are nice though, as its a quick and easy fix that might allow someone to survive long enough to see doctors instead of dying and having to be cloned

the first aid kits contain medipens among other things

**Comment by IamVelcroboy** [comment]
This was a request in wyci. Was an easy PR. So, I just did it. Not at my pc right now but I'll compare to first aid kits later. I don't remember what all comes in them. Are they consistent fills? Or rng pools?

**Comment by Vordenburg** [comment]
The blue first aid kit with the "O2" label has an emergency medipen in it.

**Comment by IamVelcroboy** [comment]
So, the Emergency Kit has 1 emergency medipen, the Advanced  Kit has 1 anti-poison pen, the, Combat Kit has 1 anti-poison pen. A case of medkits has 4 medkits, so, 4 respective pens. None of the kits have space medipens

With these, you get 10 medipens per box and 2 boxes in a crate. I feel like that's pretty significant. I could see maybe increasing the price of them maybe? (currently priced about 2.3x the actual value) Just because medipens are pretty powerful. But Ï'm not sure they're redundant...?

**Comment by ZeroDayDaemon** [comment]
Not a fan of chem reliance. these are supposed to be decently uncommon on purpose.

**Pull request closed without merging**
