### PR TITLE
add comments to recent nyano changes to upstream Content.Server

### PR DESCRIPTION
**Pull request by Elijahrane**
part of reducing further maintenance burden, we should do this to show which behavior was changed.

### CODE REVIEW

**Comment by Vordenburg** [comment]
The format of these should be standardized, likely with a start and end line.

**Comment by Vordenburg** [comment]
```csharp
        // Begin Nyano-code: check for glimmer events.
        // This could not be cleanly done anywhere else.
        if (prototype.TryGetComponent<GlimmerEventComponent>(out var glimmerEvent) &&
            (_glimmerSystem.Glimmer < glimmerEvent.MinimumGlimmer ||
            _glimmerSystem.Glimmer > glimmerEvent.MaximumGlimmer))
        {
            return false;
        }
        // End Nyano-code.
```

This is the format I used for merging Glimmer events into the new GameRule entity event system. I offer it as a suggestion.

**Comment by Elijahrane** [comment]
ok one sec

**Comment by Vordenburg** [comment]
If there are no better suggestions or criticisms in a day, we can merge this, and I'll add it to the [contributing guidelines](https://github.com/Nyanotrasen/Nyanotrasen/wiki/Contributing-Guidelines).

**Comment by Vordenburg** [comment]
I've updated the contributing guidelines. This is now the standard format.

**Pull request merged**
