### PR TITLE
it is butterbrot, the worst the thing to come out of german engineering

### PR DESCRIPTION
**Pull request by Plyushsune**
fghkyregwfwdfgrhfg

## About the PR 

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added butterbrot!
- remove: nothing

### CODE REVIEW

**Comment by Elijahrane** [comment]
this only adds the sprite and no item or anything

**Comment by Plyushsune** [comment]
Thank you Rane for the heads up, I didnt know it didnt save the yaml

**Comment by Vordenburg** [comment]
Your files should also be in `Nyanotrasen/` directories unless it is impossible to do so.

**Comment by Plyushsune** [comment]
From my current memory,  I believe the files are located in the /naynotresan/ files

**Comment by Plyushsune** [comment]
It would've been found in breads located alongside moldy slice

**Pull request closed without merging**
