### PR TITLE
Funeral Urns

### PR DESCRIPTION
**Pull request by Pspritechologist**
## Adds a Collection of urns to the game for containing ashes of the deceased, craftable by Epistemics.

Adds a standard, golden, silver, captain, space, and a few coloured ceramic urns all sprited, and craftable in the Epi Techfab after a research.
Let me know if I've done anything suboptimally here, I had to learn a lot of systems to get this done :P
I added a tag, which seems like it should be fine, and put it on Ash to seperate it as being someone's remains, limiting urns to holding only that. The wooden urn is craftable through the construction menu rather than the Techfab.

### CODE REVIEW

**Comment by Elijahrane** [comment]
should probably be under cleaning or biological tech tbh

**Comment by Pspritechologist** [comment]
> should probably be under cleaning or biological tech tbh

Awesome, I wasn't really sure what to put it under, will do!
Bluespace urn? 🤔 Can't be any less used than the trash bag :P

**Comment by ZeroDayDaemon** [comment]
- Tests Failing
- Where the hell did you even get these sprites, there's no license info at all in the meta.json

**Comment by Pspritechologist** [comment]
> * Tests Failing

Yeah, I was going to look into them, there are some other things I need to deal with anyway

> * Where the hell did you even get these sprites, there's no license info at all in the meta.json

I made 'em. Wasn't really sure what to put in there.

**Pull request closed without merging**
