### PR TITLE
Contractor Equipment

### PR DESCRIPTION
**Pull request by LittleBuilderJane**
## About the PR 
Adds a uniform, beret, backpack, magboots and three variants of Contractor Hardsuits, being unique variants of existing suits intended for a neutral, third-party group. They are meant to primarily be used in Events.
**Media**

image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Schiene
- add: Couple of Contractor variants of Clothes and Hardsuits.

### CODE REVIEW

**Comment by Elijahrane** [comment]
try pulling latest master and rerunning tests

**Comment by LittleBuilderJane** [comment]
> try pulling latest master and rerunning tests

Donezo, all checks passed !

**Comment by Elijahrane** [comment]
seems ok, check whitespace

I'll ping @OldDanceJacket since this involves armor values

**Comment by OldDanceJacket** [comment]
I'll keep these in mind when we do the armor pass in a few days, it's fine to ship these now.

**Comment by LittleBuilderJane** [comment]
> seems ok, check whitespace
> 
> I'll ping @OldDanceJacket since this involves armor values

White Space ?

**Comment by Elijahrane** [comment]
> > seems ok, check whitespace
> > I'll ping @OldDanceJacket since this involves armor values
> 
> White Space ?

it needs a few newlines added between entries

**Comment by LittleBuilderJane** [comment]
> > > seems ok, check whitespace
> > > I'll ping @OldDanceJacket since this involves armor values
> > 
> > 
> > White Space ?
> 
> it needs a few newlines added between entries

Done, I think. I mean I think so, at least ? I made sure there are lines between entries, and the formatting on all of them seems fine ?

**Comment by Vordenburg** [comment]
The last 3 sprites look washed out, not very clear, poorly defined edges. Are they just recolors of existing sprites?

All the files appear to be placed in upstream folders when they could be in Nyano-specific folders. When possible, it's best to place our own entities in our own folders to avoid merge conflicts.

**Comment by LittleBuilderJane** [comment]
> The last 3 sprites look washed out, not very clear, poorly defined edges. Are they just recolors of existing sprites?
> 
> All the files appear to be placed in upstream folders when they could be in Nyano-specific folders. When possible, it's best to place our own entities in our own folders to avoid merge conflicts.

All of them are recolors, that's literally the point...they are recolors with slightly changed stats intended to be used for independent mercenary types for Admemes.

I mean I'm not a spriter...nor a good artist..so..I'll just delete the PR if it's not high enough quality.

**Pull request closed without merging**
