### PR TITLE
Glacier Update

### PR DESCRIPTION
**Pull request by Saltson**
## Glacier Update

**Media**
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Summary**
A pretty major update to Glacier that modernises the map, adding new features, removing old and generally beautifying the map as a whole.

Major changes include a total rework for Perma, visual updates for outdoor and indoor areas, removal of the static arrivals shuttle, addition of solar arrays, fixes for a number of issues, conversion of cargo to use the teleports and generally darker more interesting maints. Full change below. This is my first PR so please tell me if I fucked anything up.

**Additional Images**
New Perma
image

New sec outpost in arrivals
image

**Changelog**

- Swapped surgery scrubber/vent so distro will chug a bit less miasma
- Added vent and scrubber to the chef's fridge
- Re-coloured all atmos pipes to fit standards
- Fixed botany/kitchen chute break
- Fixed Salv/cargo chute break
- Renamed and marked the kitchen/botany chute so chefs might stop sending their empty flower bags to the botanists and botanists will stop sending their empty robust harvest to the chefs
- Added a proper disposal chute to botany. Had to move some stuff around to do so
- Added decals and button-linked windoors to Hop queue. Make a neat line or you don't get AA
- Added more windows to open up sight lines and make corridors a bit more interesting
- Added a lot more rocky walls in the station. I liked that the original station was built into the rocks and wanted to use that motif a bit more to make the hallways more interesting
- Also in the interest of making the hallways around Hop more detailed, botany now has a market stall-style desk. But to mini fan or not to mini fan? That is the question
- Changed some windows in unrestricted spaces to be non-reinforced and changed others in restricted areas to be reinforced, but generally reduced the number of reinforced windows in public spaces. Having reinforced windows on everything makes the map feel a bit restrictive and Glacier is one of the few maps that can get off with having more regular windows, so it seems a shame to use mostly reinforced
- Made some visual changes to sec
- Added more visual scatter in maints
- Added more loot to maints
- Removed/disconnected a number of lights from maints
- Added more flashlights to maints
- Added some small veins of mineable rock to give salv a bit more to do if they feel the need
- Added a single cell charger to medical
- Added two defibs to med. One in trama and one in surgery
- Reworked outdoor pathways to look more like outdoor paving covered in snow. Not sure how I feel about this one as I liked the old tiles with the dark filter over them, but I wanted a more pronounced difference between indoors and outdoors
- Added a lot more foliage to the outdoor areas, again, just to make them seem more outdoors
- Chef starts with a few more ingredients. Iv noticed that as a chef on Glacier, you are often without a botanist so this might help a bit to get some starting food done before you start growing your own stuff
- Changed the heads starting donuts to more accurately match their colours. This is very important
- Added the smallest, shittiest solar arrays you have ever seen. They are basically useless for powering the station, but it is nice to be able to show new players how to set up the solar arrays
- Because the solars are a thing now, the CE loses his personal solar PC but gains a wardrobe with some drip
- Added some misc items on the outside of the station for salvs to find while they mine the new ore veins
- Added a few of the guidebooks for starter or recipe-heavy jobs
- Improved signage mostly in terms of evac directions
- Added some more detail to the court and changed lockup so prisoners can better see the court while imprisoned. Makes space court a bit more engaging for criminals, even if sec doesn't let them out to testify
- Added desk bells so that the clown can steal them and drive Hop to insanity
- Mail carriers get their vending machine
- Added the matter reclaimer to disposals and its board to the lockup. Not sure if it good idea to put it there
- Swabs box added to viro and gave them the virodrobe
- The old static arrivals shuttle is gone in preparation for the real arrivals shuttle. RIP bozo.
- Moved the security outpost a bit over so that it acts as a sort of “Papers Please” checkpoint if sec feels like RPing
- Added a small clothing kiosk just after the arrivals checkpoint so that newly arrived players can get a jacket in a more natural way. Also lets players man the till and make their own shop
- Perma reworked completely. Made larger and kitted out with more stuff for prisoners to work with. It's still a shithole but it can't be made much larger without seriously reworking the surrounding areas. Armory shifted around to make space for perma
- Cargo retrofit to use teleports
- Removed shutters from Hop and similar where they overlap with windows a this no longer works

### CODE REVIEW

**Comment by Vordenburg** [comment]
Test failure on this PR is valid. Open the map in your editor of choice and delete any lines containing `- invalid`

**Comment by Saltson** [comment]
Ill take a look, thanks

**Comment by Saltson** [comment]
pain

**Comment by Vordenburg** [comment]
```
System.TimeoutException : Event took too long to trigger
```

This is actually better than what we had. Now we're back to the old days of tests failing because GitHub just took too long. For future reference, if Debug/Release passes on one operating system but fails on the other, there's a good chance that everything will pan out after one re-run of tests. I'll queue it up now.

**Comment by Saltson** [comment]
Thanks a mill. Sorry for the hassle

**Comment by Saltson** [comment]
YEEEESSS. Thanks again

**Comment by Vordenburg** [comment]
All tests passing. It's a beautiful thing.

@OldDanceJacket Would you like to officially review this?

**Comment by OldDanceJacket** [comment]
Alright after reviewing this it seems to be all in-line with what was talked about before, best thing to do is let it rip and see if the players can find any missing wires. ;D

**Review by OldDanceJacket — APPROVED** [review]

**Pull request merged**
