### PR TITLE
Remove a bunch of bloat / redundant / joke content

### PR DESCRIPTION
**Pull request by Elijahrane**
## About the PR

### CODE REVIEW

**Comment by Plyushsune** [comment]
Does this mean you are gonna remove yourself as well?

**Comment by Elijahrane** [comment]
> Does this mean you are gonna remove yourself as well?

:unamused:

**Comment by IamVelcroboy** [comment]
Why Skub? I thought we were pro-skub here.

The lid of saws is a good call though. That thing is whack.

**Comment by Elijahrane** [comment]
> Why Skub? I thought we were pro-skub here.
> 
> The lid of saws is a good call though. That thing is whack.

The clothing and item themselves are both a bit too memey with no interaction. It can be referenced elsewhere in e.g. bar signs

**Comment by Vordenburg** [comment]
Given the number of files changed, this will take some time to review. It may also collide with the upcoming cherrypick merge, but we'll see.

**Comment by Elijahrane** [comment]
> Given the number of files changed, this will take some time to review. It may also collide with the upcoming cherrypick merge, but we'll see.

get the cherry pick in first and then I'll fix conflicts

**Comment by DEATHB4DEFEAT** [comment]
no more lizard plushie D:

**Comment by IamVelcroboy** [comment]
What's the meme behind the lizard?

**Comment by Elijahrane** [comment]
> What's the meme behind the lizard?

The sound was a reference which will not be discussed, as nothing good will come from it. I guess we can keep the object itself.

**Review by Vordenburg — APPROVED** [review]
I've had a look through everything as of the latest commit. Might just need to merge master and resolve some whitespace issues.

**Comment by Elijahrane** [comment]
the EOL changes have messed with a few files here

**Review by Vordenburg — APPROVED** [review]

**Pull request merged**
