### PR TITLE
Centers condiment machine

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Changelog:

- Centers the condiment machine on tables 
image

### CODE REVIEW

**Comment by Vordenburg** [comment]
This changes the Fixture. I assume it's because it inherits from VendingMachine, so it ends up having a more rectangular bounding box otherwise? Just to be clear here. Is density 200 still necessary if we're talking about a condiment rack? It could be lighter.

**Comment by IamVelcroboy** [comment]
Yeah, I had to change the dimensions. And I just brought the density down from the parent. But considering that is a vending machines, it does make sense to reduce it. At work all day, but I'll adjust it later.

**Comment by Vordenburg** [comment]
Just need the density reduced on this a bit and we're good.

**Comment by IamVelcroboy** [comment]
Looking at other examples and seems to be another area of inconsistency. Microwave(same size as condiment dispenser) is 190. But I figured it's probably be a little lighter than that.  Reagent Grinder is also 190(inherits from BaseMachinePowered)

I was kinda thinking it wold be somewhere in the middle of those but...What do you think would be a good value?

It is technically a "powered" machine. But it's just a dispenser. Probably wouldn't be as heavy as a microwave 🤷

**Comment by Vordenburg** [comment]
Unfortunately we don't have the concept of an unpowered vending machine. If you want to make it lighter, that's fine, but I wouldn't worry about it too much given that the grinder is also almost as heavy as entire vending machine.

**Comment by IamVelcroboy** [comment]
OK, I'll just bump it down to 190 then. Seems consistent, I guess

**Pull request merged**
