### PR TITLE
Moth sprite overhaul / update

### LINKED ISSUE #1106: Moths need a direct sprite import from /tg/ and to use static coloring
## Description

Looks awful otherwise. If someone starts working on an important I can write the required coloring changes real quick.

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR
Average moth player when this gets merged

### This is a port of the SS13 /tg/ Moth sprites.

**This does the following:**
- Fix the unwashed look of the current moth sprites by replacing it with the default color.
- Fix the antennas not being changeable due to them being incorrectly placed in Snout.
- Add all the /tg/ wings, antennas and markings
  - Markings are currently cut into 6 parts each (head, chest, leftleg, rightleg, leftarm, rightarm) which makes selecting all parts a bit tedious.
  - Wings are still using the current method of cutting out the body.
- Fixes the holes in wings issue, as long as you wear a jumpsuit you shouldn't see holes anymore
- Adds the moth eyeballs organ. It does nothing gameplay wise but it's there if we ever need it.
- Remove the color customization option for the moth body, wings, antennas, markings

Resolves #1106 when finished and merged.

**Media**
_Moth eyes._
They see you. Or probably not.

_Wings, Antennas and Markings_
The whole update main reason to be.
Exemple of some combinations (pre markings fix)

**Todo list**
- [X] Export all the /tg/ moth sprites into new format for SS14
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.
- [X] Fix issue where chest marking is hidden by legs and arms as they renders above.
- [ ] Make the markings, wings, antennas and body into static color.

**Changelog**

:cl:
- add: Added 22 moth antennas, 20 moth wings, 14 moth markings set.
- remove: Removed moth color customization.
- tweak: Replaced all the moth sprites to be less washed out.
- fix: Fixed holes in the moths wings. Will be fine as long as you wear clothes.

### CODE REVIEW

**Comment by Elijahrane** [comment]
So we're on the same page, I am reworking coloring stuff some time this week

**Comment by FluffiestFloof** [comment]
> So we're on the same page, I am reworking coloring stuff some time this week

Yep waiting for that to finish and undraft this.
While the whole static coloring is the goal, it would be nice if there was a way to have a set of specific 'realistic' default colors for the body to choose from. Not a priority but it would probably calm the many moths losing their colors.

Also what's your stance on keeping a set of colorable wings, markings and antennas?

**Comment by Elijahrane** [comment]
I'd rather use static coloring period. In the original impl it was a choice rather than a technical limitation. I agree with that choice.

**Comment by Elijahrane** [comment]
I merged the coloring PR to fix skeletons, this PR can be completed with current master now

**Comment by FluffiestFloof** [comment]
> I merged the coloring PR to fix skeletons, this PR can be completed with current master now

Just did a quick local test to make sure everything was working fine and feels good to go.

**Comment by Elijahrane** [comment]
yaml linter failing

**Comment by Elijahrane** [comment]
oh you didn't merge master maybe, one sec

**Comment by FluffiestFloof** [comment]
Oh yeah my bad, didn't really thought it would be useful to merge
Forgot about the checks actually being useful

**Comment by Elijahrane** [comment]
it seems like the markings don't draw fully over the base sprite
image

this is the fully royal set with broken rendering

EDIT: It looks like the sprite has transparency? Was that added afterwards? I'll have to go reference /tg/ for how these are supposed to look

**Comment by FluffiestFloof** [comment]
The markings have transparency yes. Pulled them from tg and kept how they were transparent.

**Comment by Elijahrane** [comment]
how does a moth with the royal markings set look in /tg/ as it's currently rendered?

**Comment by Elijahrane** [comment]
image
ok it seems to be rendering correctly actually

**Review by Elijahrane — APPROVED** [review]

**Comment by FluffiestFloof** [comment]
ss+(2023-02-23+at+10 59 22)
ss+(2023-02-23+at+11 01 02)

**Pull request merged**
