### PR TITLE
Update angle.yml

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR 

There were infinitesimal changes in regards to removing "MetaData" from seemingly every entity. I assume this was a result of some recent removal of it. After light testing, this MAY have changed job spawns not working.

**Changelog**
:cl:
- fix: Added some wiring and pipes; moved a few lights.

### CODE REVIEW

**Comment by Colin-Tel** [comment]
Can confirm: this didn't fix jobs like HoP not spawning in their proper places.

**Comment by Vordenburg** [comment]
Currently, all whitelisted roles do not predictably spawn in their place due to async issues with checking for whitelist at round start.

**Comment by Elijahrane** [comment]
uhhhh, are you supposed to remove metadata from every entity?

**Comment by Colin-Tel** [comment]
> uhhhh, are you supposed to remove metadata from every entity?

To clarify, I didn't do this manually. I merely made a commit and noticed the changes.

**Pull request merged**
