### PR TITLE
Slipping requires gravity

### PR DESCRIPTION
**Pull request by jicksaw**
## About the PR 
Leander requested a change so that you can't be slipped when using a jetpack: https://discord.com/channels/968983104247185448/1089692597431308349

Slipping when there's no gravity doesn't make sense and feels janky to me, so I implemented it this way. It's a pretty big nerf to soap though.

Note that jetpacks crash on debug builds even before this change. A PR on upstream fixes that: https://github.com/space-wizards/space-station-14/pull/14752

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: jick
- tweak: Slipping requires gravity

### CODE REVIEW

**Comment by Vordenburg** [comment]
Does this prevent slipping in space in general and also on a station without gravity?

**Comment by jicksaw** [comment]
> Does this prevent slipping in space in general and also on a station without gravity?

Yes.

**Comment by Elijahrane** [comment]
the code itself looks fine, but you have to explain to the science lover soyjak why this should be merged

ilovescience

**Comment by jicksaw** [comment]
Dear Science Lover Soyjak,

Please see the enclosed diagram of a catgirl attempting to move over a surface of soup.

soup

**Pull request merged**
