### PR TITLE
New map Saucer!

### PR DESCRIPTION
**Pull request by Androofroo**
## About the PR: 
This PR adds my newset (and first!) map to the game: Saucer! a small-pop map meant to incentivize player interaction and to give a more open and clean enviroment to the player! And giving them room to try out their own gimmicks!

From an abandoned flying saucer, it's first sighting recorded back to the 1650s, Nyanotrasen's commercial branch with it's contacts have made a space-worthy research vessel, that doubles as a tourist attraction! Think about the savings!

Enjoy your social life in our station's open plaza, with a juice bar (alcohol optional) and salad bar (meat optional) besides each other! an open library  so you may reach your zen state alongside nature, and the clown's showroom where your family can have a good laugh! (disclaimer: children not allowed on board. NT insurance does not cover clown caused accidents). And many other things you should find out yourself! (Please remember to remove personal items from the station after your stay ends)

**Screenshots**

saucer-0

**Changelog**

:cl: omegaTracing

add: added a new station
add: added optimism for map's fate
remove: destroyed creator's sleep schedule.

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
bad PR

**Review by Just-a-Unity-Dev — APPROVED** [review]

**Comment by ZeroDayDaemon** [comment]
image
oriented wrong

**Comment by ZeroDayDaemon** [comment]
Why?
image

**Comment by ZeroDayDaemon** [comment]
I dunno my inital impressions of this map aren't great. I am very picky when it comes to maps

**Comment by ZeroDayDaemon** [comment]
image
1 wrong boom and the entire station is essentially spaced

**Comment by Androofroo** [comment]
Ok, i hear you all, i'll definitely revise this more in-depth and make changes as needed, at least when i release this there'll be an alternative to atlas...

I also plan on remaking this map if player's first impressions are abysmal, so... ye

**Comment by ZeroDayDaemon** [comment]
Tests are failing, please fix that before I can merge for an initial test

**Comment by Androofroo** [comment]
Wait, the error log is complaining about errors with Saltern, not Saucer...
i'll still review my map, but, i'm confused about that detail

**Comment by Elijahrane** [comment]
sure why not

**Pull request merged**
