### PR TITLE
Add Bicarchup - by Katayusha

### PR DESCRIPTION
**Pull request by Vannn4**
## About the PR 
This PR adds Bicarchup -  a mix between ketchup and bicaridine. It is toxic and vomit-inducing, but since bicaridine is a component, it also heals a small amount of brute damage.
Idea is by Katayusha, I am just implementing as requested.

**Changelog**

:cl:
- add: added Bicarchup chemical/drink and its recipe

### CODE REVIEW

**Comment by Plyushsune** [comment]
If you want, replace the desc with "The beverage of the gods"

**Comment by Leander-0** [comment]
I find it funny that when your doctor prescribes you bicaridine he will have to tell you to not eat anything with ketchup along with it.

**Comment by Plyushsune** [comment]
> I find it funny that when your doctor prescribes you bicaridine he will have to tell you to not eat anything with ketchup along with it.

I mean centcommies did say it was dangerous to ingest

**Comment by Vordenburg** [comment]
But you can just mix ketchup and bicaridine on its own...? What is this?

**Comment by Plyushsune** [comment]
> But you can just mix ketchup and bicaridine on its own...? What is this?

the best drink in existence

**Comment by Plyushsune** [comment]
> But you can just mix ketchup and bicaridine on its own...? What is this?

a blessing

**Pull request closed without merging**
