### PR TITLE
Adds ovni.yml

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR 
Ovni is a new low-population station that is intended to be the successor of Saucer.

This PR contains Ovni Station as well as the necessary file changes.
Ovni was made by omegaTracing, Old Dance Jacket, Velcroboy, Colin_Tel, and the wider mapping community of Nyanotrasen.

**Changelog**
:cl:
- add: Adds Ovni Station to the game!

### CODE REVIEW

**Comment by ZeroDayDaemon** [comment]
Won't fill the emptiness from my girlfriend leaving me but I guess its better than nothing. will merge once tests are done

**Comment by ZeroDayDaemon** [comment]
Nevermind apparently there are issues

**Comment by ZeroDayDaemon** [comment]
fix em

**Comment by Colin-Tel** [comment]
I suspect the errors are related to the pool file. If these tests fail, I will attempt to revert to pool file.

**Comment by Colin-Tel** [comment]
Nope, no clue what the deal is. Some shit with RT is failing so this may be something other than what I've changed. I dunno.

**Comment by ZeroDayDaemon** [comment]
Fuck it

**Comment by ZeroDayDaemon** [comment]
Ship It

**Comment by ZeroDayDaemon** [comment]
Someone can forcemap it for a few rounds and if nothing is fucked just PR adding it to the pool again

**Pull request merged**
