### PR TITLE
Add game mode Shipwrecked

### PR DESCRIPTION
**Pull request by Vordenburg**
Every commit is more or less atomic and represents a feature which the primary commit is dependent on. I will be doing a merge commit on this PR, as opposed to raising a dozen individual PRs, in the event forks want certain features but not others.

I think only commit 44a6fe5c554ba5caabd472f187890a5a89f49f53 is dependent on e95a51320395037f0090a657fed4324de2f753fe. The rest should be clean isolates.

This game mode has had some testing but not a thorough run through. Consider it in a beta status. I'm hoping to get some feedback from players. It is not in the Secret pool.

:cl:
- add: Added a new game mode for small servers and low player counts: Shipwrecked. Vote for it in the lobby.

EDIT:

If you selectively merge the Hologram species, make sure to take the related shader fix commits:
- 0638fe1
- e661bdb
- 7ea56cc

For future reference: SS14 shaders require precision specified for compat mode to work with them, and they may have variable names reserved on one driver/OS but not another, if anyone runs into similar problems.

### CODE REVIEW

**Comment by Elijahrane** [comment]
Huge

**Comment by Elijahrane** [comment]
Shader variables need precision specified to work in compat mode

**Comment by Vordenburg** [comment]
Alright, that should fix it.

**Comment by Elijahrane** [comment]
Shaders work in compat mode now

**Comment by Vordenburg** [comment]
I had tests pass locally, but I'll give it a moment while I update the main PR description to document my folly with shaders.

**Comment by Vordenburg** [comment]
Ubuntu debug & release passed, and that is very well for me.

**Pull request merged**
