### PR TITLE
Bartending recipes

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR 

Adds recipes for Margaritas, Vodka Tonics, Manhattans (and Manhattan Projects), Whiskey Sodas, Bahama Mamas, Allies Cocktails, Sui Dreams, and Snow Whites. All the cocktails also now metabolize into some ethanol.

**Media**

image

**Changelog**

:cl:
- add: Added recipes for some mixed drinks, as well as giving them ethanol content.

### CODE REVIEW

**Comment by Elijahrane** [comment]
they all have the same ethanol? Ethanol content is just their real life alcohol % divided by 2.

**Comment by Colin-Tel** [comment]
> they all have the same ethanol? Ethanol content is just their real life alcohol % divided by 2.

I see what you're saying. I will say that the additions I made as far as "ethanol content" were made because of the complete lack of ethanol in the mixed drinks that would be made available. I wasn't intending on it being a unique amount for each mixed drink, just that they have some.

Would you want me to vary the ethanol on the drinks instead?

**Comment by Elijahrane** [comment]
all drinks that are able to be made so far have used the drink's real world ABV as a model and I don't want to lose that

**Comment by Colin-Tel** [comment]
> all drinks that are able to be made so far have used the drink's real world ABV as a model and I don't want to lose that

Seen, I'll look them up and change them to keep in line with that precedent.

**Comment by Colin-Tel** [comment]
Tests appear to have failed for no reason.

**Comment by Vordenburg** [comment]
All tests are passing now though.

**Pull request merged**
