### PR TITLE
Service Workers Addition

### PR DESCRIPTION
**Pull request by Pspritechologist**
## Service Workers as not an intern role, but just a role that's genuinely fun for RP. Manage the tables in the diner, run food back and forth to departments, kinda fill the hole left by Assistant -> Passenger, but with an actual purpose. Also great for larger maps where there might be more than one eating area.
Left out of Atlas and Saltern due to low pop.

image

**Changelog**

:cl:
- add: Added outfit for Service Workers
- add: Added Service Workers as a role
- add: Added Service Worker spawns to Glacier
- add: Added Service Worker spawns to Boxstation
- add: Added Service Worker to Glacier prototype
- add: Added Service Worker to Lighthouse prototype
- add: Added Service Worker to Boxstation prototype
- fix: Maybe fixed the department list being weird

### CODE REVIEW

**Comment by Elijahrane** [comment]
whatever this PR does it probably shouldn't have almost 20k changed lines

**Comment by Pspritechologist** [comment]
> whatever this PR does it probably shouldn't have almost 20k changed lines

It's possible you updated after I sent the PR, but even then, some of the stuff being changed didn't look right :P
Oh well, no idea why, but it should be fixed now?

**Comment by ZeroDayDaemon** [comment]
It's from map diffs being ass

**Comment by Pspritechologist** [comment]
> It's from map diffs being ass

There were some actual issues as well, differences that shouldn't be there. Other than that, I have noticed that mapping changes read strangely :P

**Comment by Pspritechologist** [comment]
Added an outfit for Service Workers to make them feel less like a greyshirt, and more like an RP role. Valets are cool :)

**Comment by Elijahrane** [comment]
So, 3 points to consider here:
1. I want to hear a better argument for their inclusion, since kitchen roles don't seem understaffed, they just generally suck.
2. The fez has to go since that's a mantis thing now.
3. Could there be a better name?

**Comment by Pspritechologist** [comment]
> So, 3 points to consider here:
> 
> 1. I want to hear a better argument for their inclusion, since kitchen roles don't seem understaffed, they just generally suck.
> 2. The fez has to go since that's a mantis thing now.
> 3. Could there be a better name?

1. RP in general. Their job wouldn't be in the kitchen, primarily, it would be serving people. One way could be food, sure, but any other thing you need to just staff someone at? A counter, an info desk, it fills the general role of "Someone looking for a job" but does it with a bit of style, unlike Assistant/Passenger. Overall, I think it'd be a really nice role to slot in. It would also make larger scale service areas more viable, for instance having a diner seperate from a kitchen.
2. Awwwww :(. Fineeee, I'll make a silly valet hat that ISN'T a fez >:T
3. Valet! :D

**Comment by Elijahrane** [comment]
Remove the map file (not prototype) changes and make it setPreference: false, I'm fine trying it for a while in a non committal way. After variants it could probably be a variant of assistant.

**Comment by Pspritechologist** [comment]
> Remove the map file (not prototype) changes and make it setPreference: false, I'm fine trying it for a while in a non committal way. After variants it could probably be a variant of assistant.

Sounds fair to me. I like the valet outfit a lot :>
So, you want it late join only. I must admit, I'm not a big fan of roles being that, but I can compromise :P
I think it'll be fun in game, honestly, but we'll see if people take to it. Late join roles can be rough. Did you want me to change the name?

**Comment by Elijahrane** [comment]
Yeah, change the name

**Comment by Pspritechologist** [comment]
Valet was good, then?
By the way, enable antag, since it isn't an intern?

**Comment by Elijahrane** [comment]
yes and yes

**Comment by Pspritechologist** [comment]
Everything should be good and done here. Valets are now the fetchers of the station.

**Pull request merged**
