### PR TITLE
Adds the MoNoKrome Drobe and additional MNK outfits. 

### PR DESCRIPTION
**Pull request by Hyenh**
## About the PR 
An effort to avoid the clogging of the Autodrobe with the addition of a new drobe, as well as fill the station environment with an increase in casual outfits and clothing. Additionally switches the tracksuit over to the MNK fashion brand.

**Media**

image
image
image
image
image
image
image
image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added the MoNoKrome drobe and 9 new outfits.

### CODE REVIEW

**Comment by Hyenh** [comment]
I seem to have goofed.

**Comment by Vordenburg** [comment]
The YAML linter is choking on this: `1) CLIENT: 9.136s [ERRO] proto: Reading Robust.Shared.Prototypes.EntityPrototype(ClothingUniformMNKDressBlack) threw the following exception: System.ArgumentException: Requested value 'UnifromTop' was not found.`

`UnifromTop` -> `UniformTop`

**Comment by Hyenh** [comment]
I think it was a mistake trying to rename the tracksuit.

**Comment by Hyenh** [comment]
:despair:

**Comment by Vordenburg** [comment]
Seems like there was one `ClothingUniformTracksuitBlack` left mapped in on Arena station. If you want the test to pass, you'd just go in and rename it in the text of the map file itself. Normally with larger scale renames affecting maps, you'd make a migration, but I could only find one in the maps.

**Comment by Elijahrane** [comment]
We'll just do a migration, I think. For our stuff we might consider commenting them out in the future if they are unneeded and they might start to become a minor perf concern.

Getting this in as it looks like we're due for another batch of map updates.

**Comment by Vordenburg** [comment]
All of the entries in YML need proper spacing. These clothing entities should probably be in their own file at this point if there is a whole family of them. There is a capitalization inconsistency between `mnk` and `MNK` which needs to be resolved.

**Pull request merged**
