### PR TITLE
Map Overhaul

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## Changelog

Arena
- Major overhaul of arena, service and security. (see image for details)

**Media**

Arena-0

- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

:cl: Velcroboy
- tweak: Arena is now Flipadelphia. This was a major overhaul of several departments. Please report any bugs or feedback in the **mapping** channel on Nyano or Delta V Discord.

### CODE REVIEW

**Comment by Vordenburg** [comment]
```
A total of 1 test files matched the specified pattern.
  Failed GameMapsLoadableTest("Arena") [20 s]
  Error Message:
     There is no spawnpoint for SecurityCadet, Warden on Arena.
  Expected: property Count equal to 0
  But was:  2
```

**Comment by Vordenburg** [comment]
```
A total of 1 test files matched the specified pattern.
  Failed GameMapsLoadableTest("Arena") [18 s]
  Error Message:
     There is no spawnpoint for Warden on Arena.
  Expected: property Count equal to 0
  But was:  1
```

**Comment by IamVelcroboy** [comment]
errr, now what...?

**Comment by Vordenburg** [comment]
Everything's fine now. That test just timed out.

**Pull request merged**
