### PR TITLE
Disable harm mode on the arrivals terminal/shuttle

### PR DESCRIPTION
**Pull request by DebugOk**
## About the PR 
This is a rather simple change, it just makes you a pacifist until you arrive at the station from the terminal. Makes it a lot harder to beat someone to death on the terminal. Idealy it would also prevent uplink usage so you cant buy bombs, but thats something I couldn't do in 4 lines.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Debug
- tweak: Disabled harm mode on the arrivals terminal

### CODE REVIEW

**Comment by Vordenburg** [comment]
I'm not in favor of merging this at this time.

1. What if the mob is Pacified to begin with? (Traits, etc.)
2. There are more ways than just Harm mode to mess with someone.

**Comment by DebugOk** [comment]
> I'm not in favor of merging this at this time.
> 
> 1. What if the mob is Pacified to begin with? (Traits, etc.)
> 2. There are more ways than just Harm mode to mess with someone.

Mobs that didn't spawn at a late-join spawner aren't able to take the shuttle at all afaik, so that wouldn't be an issue. I can find a way to make sure it doesn't remove the component from people who had the trait.

And harm mode is the easiest way to mess with someone. If you cant turn on harm mode and still kill someone via other means like grenades or whatnot thats for admins to deal with. I didn't see a component for disabling the uplink, and that'd probably be the only realistic way you could still kill someone without harm

**Comment by DebugOk** [comment]
I just checked, the trait uses a different system for ensuring you are pacified. Probably made with Pax in mind. Thus the first problem wont present any issues. Its true that the component will be removed for a moment after you arrive, but its added right back.

image

**Comment by Vordenburg** [comment]
If that's the case, this might be alright to merge as-is. I'll have to take a closer look at Pacifist and Pacified to make sure.

**Comment by DebugOk** [comment]
Before merging, I want to have a quick look into the uplink to see if I can use the pendingclockin component to block uplink usage on the terminal

**Comment by Vordenburg** [comment]
If only we had working PDA ringtones, we could just wait till they're on station to ping them with the ringtone code.

**Comment by DebugOk** [comment]
I got it working, but now I just need a proper error message to give

**Comment by DebugOk** [comment]
Pushed a change that also blocks using all store types as long as you have the arrivals component added

**Comment by DebugOk** [comment]
Its probably better to not have someone become a syndie at all until they arrive, but that probably goes beyond my skill level

**Comment by DebugOk** [comment]
Was there anything else I should look into disabling on the arrivals terminal that might be an easy way to kill people?

**Comment by Colin-Tel** [comment]
> Was there anything else I should look into disabling on the arrivals terminal that might be an easy way to kill people?

I think another big thing to solve is the addition of shuttle walls/windows/docks that are impervious to meteors, then replacing the external-facing parts of the arrivals shuttle with those parts. 

That could be handled in another PR, however.

**Comment by DebugOk** [comment]
That falls out of the scope of what this pr was intended to do, but that would be a good idea. It'd also be nice if the shuttle parts couldn't be dissasembled, salvage _really_ likes that shuttle console + mini gravity generator

**Comment by DebugOk** [comment]
Closing it for now due to arrivals being 1984'd out of existance, I'll leave the code and branch in place if its ever decided to bring it back and upstream doesnt do something like this

**Pull request closed without merging**
