### PR TITLE
Lobby Tracks May 2023

### PR DESCRIPTION
**Pull request by SelfDrivingRiddler**
Faye

:cl:
- add: New Lobby Song
- add: New Roundend Sound
- tweak: Steve from R&D now Smokes Loud
- remove: Unpopular Lobby Song

### CODE REVIEW

**Comment by Vordenburg** [comment]
You didn't have to close your previous PR. It's also strange that you're opening this PR with a reverted commit. That could've been rebased out of your history with a drop.

**Comment by SelfDrivingRiddler** [comment]
> You didn't have to close your previous PR. It's also strange that you're opening this PR with a reverted commit. That could've been rebased out of your history with a drop.

I'm flying by the seat of my pants so thank you for all the advice and tips, I was trying to get rid of it here too but yea i did it in a silly way.

**Comment by Plyushsune** [comment]
Why are we keeping the Steve from r&d end quip?

**Comment by SelfDrivingRiddler** [comment]
its kino and i made it way better

**Comment by Plyushsune** [comment]
Explain please

**Comment by Vordenburg** [comment]
Tests failed due to time. I can re-run them.

**Comment by Elijahrane** [comment]
in august I will introduce a harsh noise track

**Comment by Vordenburg** [comment]
`evapilot.ogg` is 13MB large. Surely this can be reduced in size. Does the engine support the Opus codec? I've found it to be excellent in compression and quality. Regardless, it's a good tune. If not, you could probably do okay with an Ogg/Vorbis file that has a bitrate much, much lower than `392 kb/s`...

Do you have an attribution for `bigmoney.ogg`?

I want to say this here, not for this PR specifically but more in general: I'd like us to move towards less funny round-end/lobby audio, as part of an effort to establish a theme that isn't completely ridiculous.

**Review by Vordenburg — CHANGES_REQUESTED** [review]
See prior comment.

**Comment by SelfDrivingRiddler** [comment]
My repo is being weird even though it should be up to date, so Im probably going to just close this and remake it with a master which im certain is up to date

**Pull request closed without merging**
