### PR TITLE
moff plush

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
moth plushie

:cl: DEATHB4DEFEAT
- add: Add a moth plushie.

### CODE REVIEW

**Comment by Vordenburg** [comment]
The RSI validator is failing due to a lack of copyright and licensing information. I recommend not using a generic name like 'plushies.rsi' because we are likely to have more than just one artist who wants to contribute plushies. The Nyanotrasen poster directory structure is a better way to avoid these issues.

**Comment by ZeroDayDaemon** [comment]
Honestly considering that sprite is directly from /tg/ this should also be upstreamed

**Comment by Elijahrane** [comment]
> Honestly considering that sprite is directly from /tg/ this should also be upstreamed

wtf no it doesn't

just add license and copyright info so this doesn't make our rsi validator repeatedly fail

**Comment by DEATHB4DEFEAT** [comment]
i'll do it when i get home

**Comment by DEATHB4DEFEAT** [comment]
> when i get home

i lied, doing it now

**Pull request merged**
