### PR TITLE
Make guidebook more user-friendly.

### LINKED ISSUE #1274: Guidebook Expands all Entries at Default on Every Open
## Description
The Guidebook currently expands all sub-categories of entries at default. This may have looked like a good decision before, but we're expanding the contents in it at a fast rate, and it will soon be barely comprehensible to read all of them just to find what you want. The entries are well-labeled - I don't think we're at risk of someone missing much if they are looking for it.

Even if you do decide to collapse entries, they all expand again once the Cookbook is re-opened. Why bother have collapsible categories at that point?

This is already a lot. And with the addition of the Cookbook will become much worse.
image

**Reproduction**
1. Open the Guidebook.
2. Collapse some entries.
3. Press Num 0.
4. Observe Expand All.

### PR DESCRIPTION
**Pull request by dch-GH**
## About the PR 
Resolves https://github.com/Nyanotrasen/Nyanotrasen/issues/1274
Only expands/selects the basic Space Station 14 entry instead of expanding all entries when populating the tree (upon the first time the Guidebook is opened). I've also added a collapse/expand all button, and made the Guidebook remember where you left off when you last closed it. I feel like this makes for a better user experience.

**Media**

https://user-images.githubusercontent.com/66768086/225198893-2747853a-46e0-4a71-a305-878774b5a3ce.mp4

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Made the guidebook less overwhelming and more user-friendly.

### CODE REVIEW

**Review by Torun-S — APPROVED** [review]
Very nice. CI is a false-negative.

**Comment by dch-GH** [comment]
> Very nice. CI is a false-negative.

Yup, it happens. No worries. But yeah, should be good to go. The only thing I think might be good to add is to caching the state of the guidebook per play session/round so if a player closes it while reading a subject, they can pick up where they left off when they re-open it. Thoughts?

**Comment by Torun-S** [comment]
If you can have the client handle that, I don't see a reason why would anyone mind having that!

**Comment by dch-GH** [comment]
Ready for review.

**Review by Elijahrane — APPROVED** [review]
lgtm

**Pull request merged**
