### PR TITLE
Brain Bomb drink recipe ingredient change

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR 
Replaces every instance of THCOil with THC and removes the THCOil reagent.

**Changelog**

:cl:
- tweak: Modified Brain Bomb recipe to use THC instead of THC Oil

### CODE REVIEW

**Comment by Elijahrane** [comment]
Can't you just get it from grinding cannabis leaves?

**Comment by Vordenburg** [comment]
https://github.com/Nyanotrasen/Nyanotrasen/blob/fc9d656a5c8c2aae745503cf8cc03943e1dce3bc/Resources/Prototypes/Entities/Objects/Specific/Hydroponics/leaves.yml#L3-L19

Yes.

**Comment by FluffiestFloof** [comment]
> Can't you just get it from grinding cannabis leaves?

Cannabis seeds produces cannabis leaves that contains THC and not THCOil like the spawnable version.

**Comment by FluffiestFloof** [comment]
https://github.com/Nyanotrasen/Nyanotrasen/blob/fc9d656a5c8c2aae745503cf8cc03943e1dce3bc/Resources/Prototypes/Hydroponics/seeds.yml#L438-L459

https://user-images.githubusercontent.com/9823203/227796294-2eb17520-5299-4c4a-a555-9ec29278eaa0.mp4

**Comment by Elijahrane** [comment]
is there any reason for THC and THC oil to not be compressed into 1 reagent?

**Comment by FluffiestFloof** [comment]
> is there any reason for THC and THC oil to not be compressed into 1 reagent?

No clue. For some reason THCOil is from upstream and only used in that specific spawned in Cannabis Leave (upstream wise).
We use it in a couple of our own recipes.
I can replace every mention of THCOil with THC if you want.

**Comment by Elijahrane** [comment]
I think compressing them both into THC would be a preferable solution

**Comment by Vordenburg** [comment]
Sounds reasonable to me. Some decisions will need to be made over what the final flavor, color, etc. should be, since they both seem to have different ones, and one of them affects plant growth and the other does not. Probably best to merge those together in the final product.

**Comment by FluffiestFloof** [comment]
Actually I realized that the only recipe that makes use of THC Oil is my own drink recipes so all of this is actually not worth creating future merging issues if upstream touches THC and THCOil again one day.

I think changing that one single drink recipe is less of an hassle.

**Comment by Elijahrane** [comment]
can you actually go and delete the THCOil reagent altogether? It can still spawn with e.g. oracle juice or vent clog event.

**Comment by FluffiestFloof** [comment]
> can you actually go and delete the THCOil reagent altogether? It can still spawn with e.g. oracle juice or vent clog event.

Sure thing

**Pull request merged**
