### PR TITLE
Updated shuttle airlocks

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR 

On the Kaeri (Angle's evac shuttle) and Nyano's default evac shuttle, replaced the shuttle airlocks with ones that do not require "External" access on an equipped ID.

**Changelog**
:cl:
- fix: Fixed evac shuttle airlocks requiring "External" access.

### CODE REVIEW

**Comment by Vordenburg** [comment]
Didn't these work before just fine? I swear I remember when the shuttle docked, all external airlocks would open. I feel like there's some other underlying bug here.

**Comment by Colin-Tel** [comment]
> Didn't these work before just fine? I swear I remember when the shuttle docked, all external airlocks would open. I feel like there's some other underlying bug here.

Yes, they did. The thing is that the change in this PR is one that is relatively minor and fixes the current situation. There isn't really a *need* for the evac shuttle's airlocks being locked, as they'll still dock in the correct location. The actual bug is that the airlocks on the shuttle do not open upon docking.

**Comment by Vordenburg** [comment]
I'd prefer to fix this at the source rather than apply a patch that we may forget about. Does this issue exist on upstream?

**Comment by IamVelcroboy** [comment]
This is what upstream is doing. They have unlocked doors on their shuttles.

**Comment by Vordenburg** [comment]
My recent PR addressed the core of this issue which was CentComMap was not being unpaused in time for the shuttle to gain power to be able to open its doors upon docking.

**Comment by Colin-Tel** [comment]
> My recent PR addressed the core of this issue which was CentComMap was not being unpaused in time for the shuttle to gain power to be able to open its doors upon docking.

Seen, closing this.

**Comment by Elijahrane** [comment]
> My recent PR addressed the core of this issue which was CentComMap was not being unpaused in time for the shuttle to gain power to be able to open its doors upon docking.

Okay but without that issue, should the emergency shuttle doors be locked? I don't really see any reason to since they have tiny fans

**Comment by Vordenburg** [comment]
Anyone who is out in space should already have access to get in. If they don't, or if someone unauthorized wants to jump out into space, then the access restriction is doing what it's supposed to do as it would for the station's external airlocks.

**Pull request closed without merging**
