### PR TITLE
Animal inventory updates

### PR DESCRIPTION
**Pull request by LarsDuJour**
Hi Rane, on a previous PR you asked if I could merge some inventory templates into one file. The answer is know, since those particular creatures have a significant difference in height, requiring different offsets to avoid it look super janky.

## About the PR 

**Media**

image

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Jasper von Springen-Dingen
- add: Slimepersons and skeletons can now wear hats.
- add: Crabs now have hands and a head slot, allowing some funny dressup.
- add: Penguins now have hands, head slot and a PDA slot, allowing them to basically be crew.
- add: Crabs and penguins added to The Creature Printer at 0.01 and 1 weight respectively.
- remove: Monkeys being prohibited from using guns

### CODE REVIEW

**Comment by Elijahrane** [comment]
I don't think these animals should have hands

**Comment by LarsDuJour** [comment]
@OldDanceJacket told me to give them hands. Take it up with him,

**Comment by Elijahrane** [comment]
I'll see jacket in the ring tonight

**Comment by OldDanceJacket** [comment]
> I don't think these animals should have hands

Listen here you true blue conflicting speaking dork--You agreed to the idea of Penguins being Monkey replacements for Glacier and it's been talked about many times.


You also agreed to Crab's being allowed to be added to the cloning pool, and a requirement for that would be for them to have a hand slot. It sounds fun and I like it, and it matches with things you've previously said, so merge it.

**Comment by Elijahrane** [comment]
ok

**Comment by Elijahrane** [comment]
fix conflicts etc

**Comment by LarsDuJour** [comment]
Still concerned about the "cuffable" part

**Comment by LarsDuJour** [comment]
Issue fixed with help from @Colin-Tel 

Let's see if it passes the tests now.

**Pull request merged**
