### PR TITLE
Holy Water

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR 

This is related to the "Vampires!" forum thread suggestion.
The whole cargo buyable crate, diy box and mercury bottle might be too much for what this PR doesn't bring but I was there so...

- Adds a new reagent called HolyWater.
  - It can be created using the homemade recipe of: Wine(1) + Water(1) + Mercury(1). (Taken from SS13's Holy Water recipe)
  - It can be created by blessing it in a beaker using a bible, similar to the BloodToWine reaction.
  - It lightly heals burn damage and make you recover a small amount of blood as a placeholder utility.
  - It deals Holy damage to Unholy things and it tastes heavenly.
- Adds a new ChemistryBottle: Mercury containing 30units of Mercury
- Adds a new DrinkBottle: "flask of holy water" containing 100units of HolyWater
  - Sprite taken from BeeStation.
- Adds a new BoxCardboard: holy water kit
  - Contains 3 vials of Mercury and 1 bottle of Wine.
  - Comes with its special little decal. Credit: me I guess.
- Adds a new cargo buyable: DIY holy water crate
  - It contains one "holy water kit" and is locked in an Epistemic Crate because mercury is dangerous but any Epi members can open it.

**Media**
diykitandflask

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: added Holy Water

### CODE REVIEW

**Comment by Vordenburg** [comment]
Why not just allow BibleUsers to bless water?

**Comment by FluffiestFloof** [comment]
> Why not just allow BibleUsers to bless water?

Because I'm not smart enough to do that and it could be an alternative for crew members so they can deal with undead/vampires themselves when the BibleUsers aren't there/alive.

**Comment by Elijahrane** [comment]
i am going to add a new damage type and container within a week that this can probably get integrated with, dnm for now

**Comment by Elijahrane** [comment]
update this pr for holy damage lfg

**Comment by FluffiestFloof** [comment]
ss+(2023-02-11+at+12 50 11)
On the fly added fixing this showing on the health analyzer for the new damage group/type if it doesn't stray too far from the original PR

**Comment by Elijahrane** [comment]
can you get a spray effect maybe so you can spray it on spookies

**Comment by FluffiestFloof** [comment]
Spray done, A bit unsure about what is proper damage for this so it's 1 on ingested and 0.1 on touch.
With 0.1, it seems to deal aprox 60 damage for 100u of sprayed holy water.

**Pull request merged**
