### PR TITLE
Fix several reagents satiating vampires

### PR DESCRIPTION
**Pull request by Vordenburg**
Vampires now must survive off of blood and protein.

I made even the reagents that made you hungrier (except for prometheum) not affect hunger if you have a vampiric stomach, since it made sense in my mind.

:cl:
- fix: Vampiric creatures such as the Arachne will no longer be able to sustain themselves off of salt, sugar, slime, vitamins, ramen, and soy sauce.

(What a diet.)

### CODE REVIEW

**Comment by Elijahrane** [comment]
I'll have to revisit metabolism in general before reviewing this, there were some strange things last I checked

**Comment by Vordenburg** [comment]
Do you have anything to report?

**Comment by Elijahrane** [comment]
ah no been really busy with work this week

either way it's all upstream bugs that also affect upstream content so

**Comment by Vordenburg** [comment]
Is there something specific I can test that produces strange behavior?

**Comment by Elijahrane** [comment]
mostly just stuff doesn't metabolize sometimes

**Comment by Vordenburg** [comment]
I did some tests. Arachne are still able to metabolize blood and satiate their hunger just fine. It might take some getting used to for some players, but sources of blood are plenty. The non-blood foods might be a source of confusion though, since there's the bacon burger which has no protein but the cheese burger does. I wouldn't be surprised if there's more examples like this.

That, and the ability to drain a bloodpack, could be handled in separate PRs.

**Pull request merged**
