### PR TITLE
Ovni branch

### PR DESCRIPTION
**Pull request by Androofroo**
## About the PR: An update to ovni that adds the newer requirements and fixes some issues with the map. 

:cl:
- add: Added bigger solar panels
- add: Added the fax machine to the captain's room
- add: Fixed some of the wiring.
- remove: Removed janky stuff!

### CODE REVIEW

**Comment by Vordenburg** [comment]
You added Saucer with this PR.

**Comment by Androofroo** [comment]
FUCK- do i have to remove it, or can you just omit it? I'll see what i can do

**Comment by Androofroo** [comment]
how about that?

**Comment by Vordenburg** [comment]
So it looks like commit 045f471 is the one where you did your Ovni changes. Can you try making a new branch, fresh from an updated master, with only that commit cherry-picked? There are a lot of commits in this branch that don't seem to make sense.

**Comment by Androofroo** [comment]
Yeah, that's just me being new with github, will do

**Comment by Vordenburg** [comment]
Closing in favor of #816

**Pull request closed without merging**
