### PR TITLE
New Eden

### PR DESCRIPTION
**Pull request by IamVelcroboy**
The first map is a fully functional research station set at the edges of current space travel limitations.

>Welcome to New Eden. This research station developed at the edge of our current space travel limits is a symbol of the new frontier, the hope, and the qualities of our lives brought about by the advancements developed and curated here at Nanotrasen.

>Here, at New Eden, we will break the barriers of future space travel and all that we will encounter in the infinitum.   

The second map is the same map after an “incident” has occurred. The goal of this map is not to go about daily business as usual. Instead, the team of NT employees has arrived to investigate what happened after communications from New Eden have abruptly ceased. They will need to recon, salvage, and work together to get the station back up and running again. There will need to be a whole new level of cooperation and interaction to succeed here.

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
I cannot make Map Renders. If anyone is able to help with that, that would be greatly appreciated.

**Comment by Snowni** [comment]
Out of curiosity, who are you on the discord?

**Comment by IamVelcroboy** [comment]
I'm Velcroboy

**Comment by IamVelcroboy** [comment]
Oh what the heck, I removed the folder stuff...

**Comment by ZeroDayDaemon** [comment]
the file names are terrible, also this is failing tests

**Comment by IamVelcroboy** [comment]
Yeah, I know what tests are failing. It's something weird with putting paper in folders. I thought they had already been removed.

The file names are temp while awaiting feedback and a final version will simple be renamed to NewEden.yml/NewEdenX.yml. But I serialize my versions to prevent data loss if something happens to them.

**Comment by Elijahrane** [comment]
1) Why are there 2 maps
2) Where's all of the nyano techfabs and oracle and everything
3) What's up with botany? Just have the based satellite

**Comment by IamVelcroboy** [comment]
2 maps because before/after. Both are playable for different gameplay style. So both could be used.

I will look into those. Is there any documentation of changes from main? I am only really aware of the different jobs/changes to RD->epi/and Forensics

**Comment by IamVelcroboy** [comment]
Yeah, gave botany a "Chem Division" for fun

**Comment by Elijahrane** [comment]
> Is there any documentation of changes from main?
You need to add all of the techfabs, oracle, sophic grammateus, mail teleporter, and boxing ring

You need to replace spawns, lockers, and wardrobes where applicable

**Comment by IamVelcroboy** [comment]
Mail room, Boxing ring are in. Job spawns, lockers, wardrobes were all swapped to the best of my knowledge.

So, I'll look at these: techfabs, oracle, sophic grammateus,

**Comment by Snowni** [comment]
Oracle should be placed in either chapel or Epistemics. Although, chapel should be real close to epistemics if you're putting it in there. The sophic grammateus goes in the library.

**Comment by IamVelcroboy** [comment]
So, concerning techfabs, you want all the dept techfabs placed? I think the reason I didn't is because Epistemics would be printing them as needed? Or no?

**Comment by Elijahrane** [comment]
Every techfab, yes

**Comment by Elijahrane** [comment]
I think the X version shouldnt be votable

**Comment by IamVelcroboy** [comment]
You mean special rounds only?

**Comment by IamVelcroboy** [comment]
As in votable between rounds?

**Comment by Elijahrane** [comment]
Votable field controls whether it will rotate to normally

**Comment by IamVelcroboy** [comment]
OK, errors fixed. Overall, what are your thoughts? I know the X version is different and may take some playtesting to really balance. I maybe went overboard with the destruction? or maybe not enough? But I'm open to feedback.

And if anyone is able to get renders, that would help a lot.

**Comment by Elijahrane** [comment]
the base version looks ok, I have no interest in running x

botany should be contained on the satellite and the on-station botany area can be service commons

**Comment by IamVelcroboy** [comment]
Curious what you don't like about X? like I said, I'm open to making changes, even significant ones. I think the concept would be fun though. Do you not?

**Comment by Elijahrane** [comment]
x is fine but not in normal rotation

**Comment by IamVelcroboy** [comment]
OK, so like, would you be interested in running it on special occasions/events? Or just not at all? Just wondering how much effort to put into it?

**Comment by IamVelcroboy** [comment]
Oh, thoughts on putting a psychologist office where the smaller botany is? I ran out of room in other areas for it.

**Comment by Elijahrane** [comment]
> Oh, thoughts on putting a psychologist office where the smaller botany is? I ran out of room in other areas for it.

Seems okay

**Comment by IamVelcroboy** [comment]
OK, done on base map. Will update X map with same changes later.

image

**Pull request merged**
