### PR TITLE
adds new plush

### PR DESCRIPTION
**Pull request by Plyushsune**
autism plush

## About the PR 

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added plush
- remove: Removed fun!

### CODE REVIEW

**Comment by Plyushsune** [comment]
let me test

**Comment by Plyushsune** [comment]
turns out i forgot to pr the meta.json

**Comment by Plyushsune** [comment]
image

**Comment by Vordenburg** [comment]
You can run tests and the linter locally before pushing public. This is a good practice.

**Comment by Plyushsune** [comment]
> You can run tests and the linter locally before pushing public. This is a good practice.

Thanks nice to know

**Comment by Plyushsune** [comment]
We are so back baby

**Comment by Plyushsune** [comment]
I have not forgotten about this pr

**Comment by Plyushsune** [comment]
Closing these as im gonna assume the development side of nayno is completely dead without magil

**Pull request closed without merging**
