### PR TITLE
Food Carts

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR 
- Adds hot and cold food carts
- ~~Adds tags for hot/cold foods to be accepted to appropriate cart~~

https://github.com/Nyanotrasen/Nyanotrasen/assets/107660393/8218b0ff-e6d1-4df9-a1d2-43b1cff824ec

**Media**
- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

**Changelog**

:cl: Velcroboy and Rosy!
- add: Added food carts

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Just considered this...should I make a cargo crate for these?

**Comment by Vordenburg** [comment]
Test failure is relevant. All components should be declared explicitly. Might just need ContainerManager added. I glanced through the yml after seeing that and noticed there seem to be tags for food temperature. I can say that's going to be iffy, especially with having to touch all of these SS14 files.

**Comment by IamVelcroboy** [comment]
> I glanced through the yml after seeing that and noticed there seem to be tags for food temperature. I can say that's going to be iffy, especially with having to touch all of these SS14 files.

Sure, I sort of expected that. Not sure if it's best to just allow these to essentially be crates on wheels? or if there's another way to limit what they accept short of a huge black/white list?

**Comment by Vordenburg** [comment]
It's just going to be a maintenance nightmare for not much gain beyond these two specific containers. What's the problem that's trying to be solved here? Specifically limiting what items can go in which cart?

**Comment by IamVelcroboy** [comment]
Yeah basically. I think in an ideal future we have heating/cooling mechanics. So, it would be counterintuitive to put hot->cold, visa/versa. 

I don't mind removing the tags. I just wanted it to be considered.

**Comment by Vordenburg** [comment]
I'd say so long as the carts can't be abused in terms of their storage space, it should be okay to let people put anything in them. This is one of those cases where it'd be better to implement the system desired (heating, cooling) or leave it empty/N.Y.I. than try to patch it with something that will require constant maintenance anytime new food items are added.

Heuristics are better than explicit lists.

We could make a component that whitelists storing entities inside something by checking prototype ID, and that would definitely reduce the overhead, but it's a patch of a different sort.

If these items had some innate temperature information, then that could be used, either to influence or block storage.

**Comment by IamVelcroboy** [comment]
Yeah, understandable.

I'll just remove them then and fix the container error. 

Should I add the cargo crates? I already put them together last night.

**Comment by Vordenburg** [comment]
Having certain items arrive in crates doesn't work too well if they can't be put back inside, see janitor mop buckets in crates. If it's orderable through cargo, it should come just as it is, unless there's some issue with that.

**Comment by IamVelcroboy** [comment]
I did it the same way ATV does it, it uses a livestock crate. Not sure if there's any issues with that?

**Comment by IamVelcroboy** [comment]
But I'll be testing the other changes in just a min, so I'll check for that specific issue.

**Comment by IamVelcroboy** [comment]
Ok tested the cargo crates, and yeah, it's the same as with atvs, they cannot be put back into the crate. Not sure how that affects the decision to include or not?

**Comment by IamVelcroboy** [comment]
I don't see anything in that error that pertains to the food carts any more, but let me know if it does.

**Comment by Vordenburg** [comment]
```
A total of 1 test files matched the specified pattern.
  Skipped TestAlertManager [< 1 ms]
  Failed TestDeleteCharacter [45 s]
  Error Message:
   System.InvalidOperationException : Released on different thread than took lock???
```
I've never seen that one before. I'm more than certain it's irrelevant to your feature. I'll trigger a re-run just in case.

**Comment by Vordenburg** [comment]
I want to do another pass over this later, but is there any reason why we couldn't send this to SS14 after it's been thoroughly reviewed?

**Pull request merged**
