### PR TITLE
pebble update

### PR DESCRIPTION
**Pull request by Plyushsune**
added a diorama and fixed a mapping error from the og creator

## About the PR 

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!

### CODE REVIEW

**Comment by Elijahrane** [comment]
any screenshots of changes? and which error did you fix?

**Comment by Plyushsune** [comment]
> any screenshots of changes? and which error did you fix?

Colin brought up the fact that there was firelock doors leading to maintenance which is apparently bad I guess

**Comment by Elijahrane** [comment]
@OldDanceJacket can you check this out rq

**Comment by Plyushsune** [comment]
I think I made a mistake so I'm gonna take a once over this pr because I don't accidentally pr the wrong pebble

**Comment by Plyushsune** [comment]
image
image
image
image
@rane

**Comment by Plyushsune** [comment]
also i updated it to include the new mass media console and the diorama is self examplatory

**Pull request closed without merging**
