### PR TITLE
Better dummy names (no more confusing spawn menu)

### PR DESCRIPTION
**Pull request by ZeroDayDaemon**
## About the PR 

**Screenshots**

**Changelog**

:cl: Daemon
- tweak: Tweaked Entity Names.

### CODE REVIEW

**Comment by ZeroDayDaemon** [comment]
DNM

**Comment by ZeroDayDaemon** [comment]
Still do not merge

**Comment by Elijahrane** [comment]
isn't the issue more they just need to consistently have nospawn?

**Comment by ZeroDayDaemon** [comment]
> isn't the issue more they just need to consistently have nospawn?

no

**Pull request merged**
