### PR TITLE
Unlocks the airlocks

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Changelog:
-Updates the BC20 Emergency Shuttle to have unlocked airlocks

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Magil is this change ok? I imported the map after the changes you made regarding weird behavior. I saved as grid. I didn't actually touch this node at all, only replaced the airlocks. So not sure why it changed from invalid to 2? and not sure if that's an issue?
image

**Comment by IamVelcroboy** [comment]
also, 
image
image

Not anything I touched

**Comment by Colin-Tel** [comment]
There are plenty of things that change in a map even if you don't touch them. If all you did was change the airlocks, you should be fine.

**Comment by IamVelcroboy** [comment]
Cool, just checking, as I didn't want to reintroduce an issue.

**Comment by Vordenburg** [comment]
Did you map this using the latest pull from the repository?

**Comment by IamVelcroboy** [comment]
> Did you map this using the latest pull from the repository?

I did. I pulled just before making the changes.

**Comment by Vordenburg** [comment]
A map was somehow created in this diff.

**Comment by IamVelcroboy** [comment]
I definitely used savegrid not savemap.....I'm confused how this happened?

**Pull request merged**
