### PR TITLE
Wielded Mop and Hairball icon

### PR DESCRIPTION
**Pull request by QuizzyQuin**
## About the PR 

**Media**

Screenshot 2023-01-19 090114
Screenshot 2023-01-19 090433
Screenshot 2023-01-19 090515
sponchbobMop

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: QuizzyQuin
- add: Added new wielded Mop sprite and hairball icon sprite

### CODE REVIEW

**Comment by Vordenburg** [comment]
The `remove` line is unnecessary because it's implied by the `add` line. Do you have screenshots of what these look like in game? We can already see what the images look like in the diffs.

**Comment by QuizzyQuin** [comment]
gotcha, Can I edit this Pull Request to delete the remove?

Also, better screenshots
Screenshot 2023-01-19 094647
Screenshot 2023-01-19 094944

**Comment by Vordenburg** [comment]
There's an edit option under the three dots button at the top right of your post.

**Comment by QuizzyQuin** [comment]
Thank you, updated

**Pull request merged**
