### PR TITLE
Hammurabi

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Changelog:

- Adds Hammurabi Prison Station
- Adds NTES Centipede evac shuttle

Desc: Hammurabi has a fully functional prison that opens up many activities for prisoners, such as kitchen/hydroponics work, Mining and a machine shop. They have their own jani closet and two commons areas as well as a dedicated medbay. 

The prison is set up to hold 12 prisoners and be overlooked by a new Prison Guard role that answers to the warden.  This role comes with a new uniform created by Hyenh. 

A conveyor system has been setup between the asteroid, machine chop and salvage to encourage some interplay between these areas.

The rest of the station functions as usual with all the normal roles you'd expect. Security can operate as normal since they will not be pulled away to monitor prisoners unless it is an emergency. 

Hammurabi-0

:cl:
- add: Added new map Hammurabi Prison Station!

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
I'll need to re-add the Pool file. It caused an error for some reason.

**Comment by Elijahrane** [comment]
@OldDanceJacket can you review the actual map

**Comment by IamVelcroboy** [comment]
I can't really tell what the problem is. It's something with the PDA visualizer, and I think those were changed recently but I'm not sure what needs to change?

**Comment by IamVelcroboy** [comment]
Updated the render

**Comment by IamVelcroboy** [comment]
Pretty sure that one's not me

**Comment by OldDanceJacket** [comment]
Yolo

**Pull request merged**
