### PR TITLE
long awaited pebble update

### PR DESCRIPTION
**Pull request by Plyushsune**
ghdjfgkjhjkkjhgfugdyhfstgdsd i have depression

## About the PR 

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!

### CODE REVIEW

**Comment by Vordenburg** [comment]
Are you able to resolve the merge conflict?

**Comment by Plyushsune** [comment]
> Are you able to resolve the merge conflict?

I haven't tried but I have no idea of how to fix it.
I assume it's because of the escape pods I removed.

**Comment by Vordenburg** [comment]
Merge master and look at what git reports as conflicts.

**Comment by Plyushsune** [comment]
I look into it

**Pull request closed without merging**
