### PR TITLE
Map edits

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR 

Adjusted Angle and Shoukou, added cargo bounty computers to their cargo areas.

**Changelog**

:cl:
- add: Added cargo bounty computers to Angle & Shōkō.

### CODE REVIEW

**Comment by Vordenburg** [comment]
Cargo bounty computers are not meant to be mapped in.

**Comment by Colin-Tel** [comment]
> Cargo bounty computers are not meant to be mapped in.

Oh damn really? Is there any particular reason why? I would've thought it would be cool to have little things for cargo to ask other departments to provide.

**Comment by Vordenburg** [comment]
It has to be evaluated against the supply & demand feature, and the bounties themselves are mostly jokes.

**Comment by Colin-Tel** [comment]
Well alright. Is there any chance they'll be mappable sometime in the near future, or should I just close this branch?

**Comment by Vordenburg** [comment]
I don't have S&D v. bounty consoles very high on my priority list, given the other issues that need to be addressed.

Were those the only changes you made to this branch? If so, you may close this branch.

**Pull request closed without merging**
