### PR TITLE
Added Corncob Crust Pizza. Thank rosy!

### PR DESCRIPTION
**Pull request by Torun-S**
## About the PR 
Added this in a rush before class. Least I know I can do it in half an hour, but this is thoroughly untested yet. Still, I've gotten good at writing the prototypes, but I'll check it later if it's not merged yet.
**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Torun
- add: Added Corncob Crust Pizza.

### CODE REVIEW

**Comment by FluffiestFloof** [comment]
"Tastes like a sick joke and like medicine."
Recipe and items works fine.

**Comment by Torun-S** [comment]
> "Tastes like a sick joke and like medicine." Recipe and items works fine.

Oh, shit, the medicine...
I'd have to implement a new reagent that metabolizes into Ipecac to hide that... Do I hide it?

**Comment by Torun-S** [comment]
Polished, tested. Ready to get this joke in @Elijahrane

**Comment by Elijahrane** [comment]
nausium looks like a good reagent to be added to other things in the future

**Pull request merged**
