### PR TITLE
Cherry pick thermomachine fix

### PR DESCRIPTION
**Pull request by Elijahrane**
We got the commit that introduced this bug but missed its fix.

### CODE REVIEW

**Comment by Vordenburg** [comment]
What are the commits in question?

**Comment by Elijahrane** [comment]
image
We only have the bottom commit, which introduced a bug the top one fixed

**Review by Vordenburg — APPROVED** [review]
Well, this is partially correct.

https://github.com/Nyanotrasen/Nyanotrasen/commit/d1d87df9c6

We have the commit's contents independent of #15802, because that one was skipped at the time. So this is a completion of the original cherry-pick. Alright, looks good to me.

**Comment by Vordenburg** [comment]
This overwrote a3968dbe9fd9dbee22a2059911287cd7658b1733. I will fix it.

**Comment by Vordenburg** [comment]
Original commit re-picked in #1709

**Pull request merged**
