### PR TITLE
Fix atlas medical salvage wreck

### PR DESCRIPTION
**Pull request by DebugOk**
Atlas medical now should't crash anymore, I somehow managed to PR the wrong file.

Would be cool if someone could test it before it was merged, I did it myself and found no issues but who knows

### CODE REVIEW

**Comment by Elijahrane** [comment]
Fix conflicts and confirm it works when spawned via salvage magnet, I believe there's a command to force the next salv map

**Comment by IamVelcroboy** [comment]
Do you want me to just fix this fresh on my end? Since I have the original map before any changes? All it is is removing the waffles, yeah?

**Comment by Elijahrane** [comment]
yeah, sure

**Comment by DebugOk** [comment]
Yeah go for it, I kinda forgor

**Comment by DebugOk** [comment]
Also make sure you revert https://github.com/Nyanotrasen/Nyanotrasen/pull/1531 if you do pr it

**Pull request closed without merging**
