### PR TITLE
Increased monkey cube crate price

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR 

This is to address cargo selling monkey corpses at a marginal profit.

### CODE REVIEW

**Comment by Elijahrane** [comment]
To be clear, what is happening right now with the monkey corpses? We're supposed to have tests to detect arbitrage opportunities like that.

**Comment by Leander-0** [comment]
Also, upping up the price of the monkey cubes will negatively impact the chef/epi gameplay since i will be way too expensive to buy monkey meat for food or monkeys for artifact experiment, it would be much better to lower the the price of monkey corpses to the ground that way it would be impossible to generate revenue from selling them.

**Comment by Colin-Tel** [comment]
> To be clear, what is happening right now with the monkey corpses? We're supposed to have tests to detect arbitrage opportunities like that.

Essentially: Cargo buys monkey cubes, whacks them all, then sells the corpses at around 1-1.5k profit. Perhaps the arbitrage test doesn't check it because it checks the sell price of the contents (aka the wrapped monkey cubes)?

> Also, upping up the price of the monkey cubes will negatively impact the chef/epi gameplay since i will be way too expensive to buy monkey meat for food or monkeys for artifact experiment, it would be much better to lower the the price of monkey corpses to the ground that way it would be impossible to generate revenue from selling them.

Well yeah there's a few different ways this could be done. We could raise the box price, lower the amount of monkey cubes in the purchased crate, or lower the selling price of the corpses. Personally, I didn't think raising the price for *instant monkeys* was that painful of a thing to do, since you get so many; not to mention they are not the only meat you could get from cargo.

**Comment by Elijahrane** [comment]
We'll have to have a look at what is going on with the corpses. Dead mobs are supposed to be nearly worthless.

**Comment by Vordenburg** [comment]
> To be clear, what is happening right now with the monkey corpses? We're supposed to have tests to detect arbitrage opportunities like that.

Arbitrage isn't aware of the value of an entity which turns into another entity via Rehydratable.

I put a dead monkey on a pallet. It appraises at $0. Needs more information and should be brought to SS14 if reproducible.

**Comment by Colin-Tel** [comment]
> Arbitrage isn't aware of the value of an entity which turns into another entity via Rehydratable.
> 
> I put a dead monkey on a pallet. It appraises at $0. Needs more information and should be brought to SS14 if reproducible.

Ahhh, I see. This is a Delta V exclusive issue. Monkey corpses on Nyano are not sellable and are not listed as "number of sale items" on the Cargo Sale Console when they are present on the cargo pallets.

**Pull request closed without merging**
