### PR TITLE
Added new salvage map researchpost.yml

### PR DESCRIPTION
**Pull request by fallingmonkey**
New salvage map, testing to see if it passes PR test.

### CODE REVIEW

**Comment by Elijahrane** [comment]
good job on modifying the prototype, as GH tests are broken I'll have a look locally

**Comment by Elijahrane** [comment]
fixed the proto and viewed in mapping:
1. You really want an artifact spawner instead of choosing one of the artifacts, especially with the new artifact system
2. use salvage parts spawners. the most common issue here is you are spawning specific items when you should be using spawners
3. remove the space ninja stuff

**Comment by fallingmonkey** [comment]
Oh man I can't believe I missed a " thanks for spotting that.

I'll load it up and make the recommended changes now and see how it goes

**Comment by fallingmonkey** [comment]
Going to close and PR again so I can fill it all out properly

**Pull request closed without merging**
