### PR TITLE
Remove pointless Syndicate items

### PR DESCRIPTION
**Pull request by Vordenburg**
Removes all the pointless Syndicate items but adds a useful item: sunglasses.

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Could some of these be added to fluff/clothing/rng spawners? Or are they still too associated with Syndicate. I'm thinking like the outlaw hat, maybe cat ears, etc.

**Comment by Vordenburg** [comment]
I think the outlaw hat could be added to a spawner without issue.

**Comment by Vordenburg** [comment]
The outlaw hat is already on `HatSpawner`

**Comment by IamVelcroboy** [comment]
> The outlaw hat is already on `HatSpawner`

Oh, well there ya go then

**Pull request merged**
