### PR TITLE
Fix for the Discord announcements

### PR DESCRIPTION
**Pull request by DebugOk**
## About the PR 
This introduces some fixes for https://github.com/Nyanotrasen/Nyanotrasen/pull/1393 that was merged yesterday as requested by Daemon, but since I wasn't sure on a couple of things I'll make this a draft for now.

First of all, I don't know what colors I should use for the 3 messages.
Secondly, you wanted me to "unhardcode" the color, and I'm not sure if you meant what is currently in this PR or make it a variable, so I'll do whichever.

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by DebugOk** [comment]
@ZeroDayDaemon Please see the above

**Comment by ZeroDayDaemon** [comment]
> First of all, I don't know what colors I should use for the 3 messages.

Blue for starting, green for started, and red for ended?



> Secondly, you wanted me to "unhardcode" the color, and I'm not sure if you meant what is currently in this PR or make it a variable, so I'll do whichever.

I meant like make it a cvar but honestly its not really necessary

**Comment by ZeroDayDaemon** [comment]
plus having 3 cvars for the colors is a bit bloaty so its fine as is now I suppose

**Comment by DebugOk** [comment]
I agree that 3 cvars would get cluttered, its not an issue for me to add them, but with how I currently added the colors it should be fairly easy to switch them out regardless. With that I'll be marking this ready for review

**Comment by DebugOk** [comment]
Discord_K664qN9frq
These are currently the colors, and it'll only ping on the round starting message

**Comment by ZeroDayDaemon** [comment]
looks good to me, will wait for tests and if everything is solid ill merge

**Comment by DebugOk** [comment]
Average integration test failure, is this something I fucked up or just the tests being weird like usual?

**Comment by ZeroDayDaemon** [comment]
rerunning failed jobs

**Comment by DebugOk** [comment]
Epic unfailed build

**Comment by ZeroDayDaemon** [comment]
yeah the inconsistency with these tests makes me think they're just being all fucky wucky rn so ill merge

**Pull request merged**
