### PR TITLE
Adds New Map: The Hive

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR:
Adds New Map: The Hive 
A more streamlined map with no specific gimmicks(ex: Arena/Prison/etc). Just 100% pure Space Station.

**Media**
TheHive-0

**Features**
- Internal space areas with multiple POA for fun new gameplay
- Extensive network of maints providing multiple paths to pretty much any destination
- Split energy grid 
- Most compact map Velcroboy has ever made😋
- Many new RP areas include, pet store, casino behind the bar(gambling just a week away), kitchen with food carts, and a live audience talk show studio, and many more!
ntdaily
Screenshot 2023-07-22 121353

- [x] I have added screenshots/videos to this PR showcasing its changes in-game, **or** this PR does not require an in-game showcase

**Notes**
- ~~Not present in the render are some edits to the internal lattice(areas of plating and/or missing lattice here/there.)~~
- ~~Not fully tested with arrivals shuttle yet(kinda forgot.) But I don't see an issue here until arrivals is utilized again.~~ Will probably need either anew shuttle or some adjusting if arrivals is turned back on. Not overly concerned about this right now. But should be noted if any downstreams have it on.
- ~~Pending further discussion, some/all meteor nets may be removed.~~ Going to hold off on this and keep what is current for now.

:cl: Velcroboy
- add: Added new map! The Hive

### CODE REVIEW

**Comment by Plyushsune** [comment]
Is it maintenance goblin catpatible?

**Comment by IamVelcroboy** [comment]
> Is it maintenance goblin catpatible?

No goblins. Gremlins though....

**Comment by IamVelcroboy** [comment]
Updated notes and render. Going to turn off draft as it's ready to go.

**Comment by IamVelcroboy** [comment]
Almost made it. Don't think that's on me though.

**Comment by Elijahrane** [comment]
Taking a look now. I'll want @OldDanceJacket to take a look, too, since I'll be more focused on technical rather than design issues.

**Comment by Elijahrane** [comment]
- The firelocks, air alarms, etc seem decently well equipped to handle the internal spaced areas. Good job there.

- You have an entity called "SpawnVehicleAntagVehicle." It's clear this is probably not intended for mapping a normal station.
image

- There are 25 different animal spawns, including spawners and crates. This seems a bit much, especially because some of those like the duck crate spawn a lot of NPCs.

**Comment by IamVelcroboy** [comment]
Animal spawns are pretty on par with the other maps, but with a few extra for the pet store, some new pets(Willow, Smile, Ferret, some others, I forget all of them.

I can remove the vehicle spawner, I thought it spawned normal vehicles with a chance of antag, just looked and it's only the antag ones 🤷.

**Comment by Vordenburg** [comment]
Merging for publish and the event tomorrow as scheduled. Time to get some playtesting on this one.

**Pull request merged**
