### PR TITLE
Among Pequeno with combat knife - new uplink item

### PR DESCRIPTION
**Pull request by Guess-My-Name**
## About the PR 
Adds a new uplink item - among pequeno plushie with combat knife in storage.
Currently put into Misc category, with 4 TC cost.

**Media**

new entities
storage
uplink

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added new uplink item 'Among Pequeno'

### CODE REVIEW

**Comment by Elijahrane** [comment]
seems like a bloat item

**Comment by Vordenburg** [comment]
I don't see the point of this, either.

**Comment by Guess-My-Name** [comment]
Sorry for late response
Idea was to give traitors a melee weapon that wasn't a obvious traitor item, but also to leave trail behind
And imo it would be funny to see security search and be suspicious of every pequeno they see, if this would be a known traitor item ingame.
Currently any melee weapon from uplink makes a person confirmed syndicate

**Comment by ZeroDayDaemon** [comment]
I'm not sure about this, closing for now.

**Pull request closed without merging**
